import { MAX_ARCHIVE_BYTES,MAX_TAR_BYTES,githubFail,sha } from './config.js'
import { bounded } from './http.js'
const dec=new TextDecoder('utf-8',{fatal:true}), enc=new TextEncoder(); const attest='.well-known/warpkeep-deployment-v1.json'
export type PagesArtifactDigests=Readonly<{githubArtifactArchiveSha256:string;innerArtifactTarSha256:string;contentManifestSha256:string;deploymentAttestationSha256:string;deploymentAttestationBytes:Uint8Array}>
async function digest(v:Uint8Array){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',Uint8Array.from(v)))).map(x=>x.toString(16).padStart(2,'0')).join('')}
function n(v:Uint8Array,o:number,l:number){if(o+l>v.length)githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');return l===2?new DataView(v.buffer,v.byteOffset,v.byteLength).getUint16(o,true):new DataView(v.buffer,v.byteOffset,v.byteLength).getUint32(o,true)}
function str(v:Uint8Array){try{return dec.decode(v)}catch{return githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID')}}
function size(v:Uint8Array){const s=str(v).replace(/[\0 ]+$/u,'').trimStart();if(!/^[0-7]+$/u.test(s))githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');const x=Number.parseInt(s,8);if(!Number.isSafeInteger(x)||x<0||x>MAX_TAR_BYTES)githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');return x}
function path(v:string){if(v.length<1||v.length>1024||/[\\\0-\x1f\x7f]/u.test(v)||v.startsWith('/')||v.split('/').some(x=>x===''||x==='.'||x==='..'))githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');return v}
function validAttest(v:Uint8Array){try{const x:unknown=JSON.parse(str(v));if(typeof x!=='object'||x===null||Array.isArray(x))githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');const o=x as Record<string,unknown>,k=['candidateCommit','candidateTree','canonicalOrigin','contentManifestSha256','recoveryAuthorizationCoreSha256','releaseVersion','sourceClosureSha256'];if(Object.keys(o).length!==k.length||k.some(z=>!Object.hasOwn(o,z))||typeof o.candidateCommit!=='string'||typeof o.candidateTree!=='string'||o.canonicalOrigin!=='https://warpkeep.com'||o.releaseVersion!=='0.4.0'||!sha(o.contentManifestSha256)||!sha(o.recoveryAuthorizationCoreSha256)||!sha(o.sourceClosureSha256))githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID')}catch{return githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID')}}
export async function inspectPagesArtifact(response:Response):Promise<PagesArtifactDigests>{const outer=await bounded(response,MAX_ARCHIVE_BYTES,'RECOVERY_GITHUB_ARCHIVE_INVALID');if(n(outer,0,4)!==0x04034b50||n(outer,6,2)!==0||n(outer,8,2)!==0)githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');const compressed=n(outer,18,4),uncompressed=n(outer,22,4),name=n(outer,26,2),extra=n(outer,28,2),start=30+name+extra;if(compressed!==uncompressed||compressed>MAX_TAR_BYTES||start+compressed!==outer.length||str(outer.slice(30,30+name))!=='artifact.tar')githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');const tar=outer.slice(start),seen=new Set<string>(),folded=new Set<string>(),manifest:Array<{path:string;size:number;sha256:string}>=[];let at:Uint8Array|undefined,offset=0,end=false;while(offset+512<=tar.length){const h=tar.slice(offset,offset+512);if(h.every(x=>x===0)){if(tar.slice(offset,offset+1024).every(x=>x===0)){offset+=1024;end=true;break}githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID')}if(str(h.slice(257,263))!=='ustar\0'||str(h.slice(263,265))!=='00'||h[156]!==48||str(h.slice(157,257))!=='')githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');const prefix=str(h.slice(345,500)).replace(/\0.*$/u,''),namePart=str(h.slice(0,100)).replace(/\0.*$/u,''),p=path(prefix===''?namePart:`${prefix}/${namePart}`),s=size(h.slice(124,136)),begin=offset+512,padded=Math.ceil(s/512)*512;if(begin+padded>tar.length||seen.has(p)||folded.has(p.toLowerCase())||tar.slice(begin+s,begin+padded).some(x=>x!==0))githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');seen.add(p);folded.add(p.toLowerCase());const body=tar.slice(begin,begin+s);if(p===attest)at=body;manifest.push({path:p,size:s,sha256:await digest(body)});offset=begin+padded}if(!end||offset!==tar.length||at===undefined)githubFail('RECOVERY_GITHUB_ARCHIVE_INVALID');validAttest(at);manifest.sort((a,b)=>a.path.localeCompare(b.path));return Object.freeze({githubArtifactArchiveSha256:await digest(outer),innerArtifactTarSha256:await digest(tar),contentManifestSha256:await digest(enc.encode(JSON.stringify(manifest.filter(x=>x.path!==attest)))),deploymentAttestationSha256:await digest(at),deploymentAttestationBytes:at})}
