// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AdminGetAlphaStatusProcedure from "../admin_get_alpha_status_procedure";
import * as AdminGetAlphaStatusV2Procedure from "../admin_get_alpha_status_v_2_procedure";
import * as AdminGetAlphaStatusV3Procedure from "../admin_get_alpha_status_v_3_procedure";
import * as AdminGetAlphaStatusV4Procedure from "../admin_get_alpha_status_v_4_procedure";
import * as AdminGetAlphaStatusV8Procedure from "../admin_get_alpha_status_v_8_procedure";
import * as AdminGetFidAuthEpochProcedure from "../admin_get_fid_auth_epoch_procedure";
import * as AdminGetSnapScanBatchAggregateV1Procedure from "../admin_get_snap_scan_batch_aggregate_v_1_procedure";
import * as AdminInspectGenesisWaterLayoutV1Procedure from "../admin_inspect_genesis_water_layout_v_1_procedure";
import * as AuthResolverGetFidAdmissionV2Procedure from "../auth_resolver_get_fid_admission_v_2_procedure";
import * as GetAlphaBackendInfoProcedure from "../get_alpha_backend_info_procedure";
import * as GetMyAdmissionStatusProcedure from "../get_my_admission_status_procedure";
import * as GetMyAdmissionStatusV2Procedure from "../get_my_admission_status_v_2_procedure";
import * as GetMyFoodExpeditionStateV1Procedure from "../get_my_food_expedition_state_v_1_procedure";
import * as GetMyGoldExpeditionStateV1Procedure from "../get_my_gold_expedition_state_v_1_procedure";
import * as GetMyResourceStateV1Procedure from "../get_my_resource_state_v_1_procedure";
import * as GetMyWoodExpeditionStateV1Procedure from "../get_my_wood_expedition_state_v_1_procedure";
import * as QaObserverGetRealmAttestationV2Procedure from "../qa_observer_get_realm_attestation_v_2_procedure";
import * as QaObserverGetRealmSnapshotV1Procedure from "../qa_observer_get_realm_snapshot_v_1_procedure";

export type AdminGetAlphaStatusArgs = __Infer<typeof AdminGetAlphaStatusProcedure.params>;
export type AdminGetAlphaStatusResult = __Infer<typeof AdminGetAlphaStatusProcedure.returnType>;
export type AdminGetAlphaStatusV2Args = __Infer<typeof AdminGetAlphaStatusV2Procedure.params>;
export type AdminGetAlphaStatusV2Result = __Infer<typeof AdminGetAlphaStatusV2Procedure.returnType>;
export type AdminGetAlphaStatusV3Args = __Infer<typeof AdminGetAlphaStatusV3Procedure.params>;
export type AdminGetAlphaStatusV3Result = __Infer<typeof AdminGetAlphaStatusV3Procedure.returnType>;
export type AdminGetAlphaStatusV4Args = __Infer<typeof AdminGetAlphaStatusV4Procedure.params>;
export type AdminGetAlphaStatusV4Result = __Infer<typeof AdminGetAlphaStatusV4Procedure.returnType>;
export type AdminGetAlphaStatusV8Args = __Infer<typeof AdminGetAlphaStatusV8Procedure.params>;
export type AdminGetAlphaStatusV8Result = __Infer<typeof AdminGetAlphaStatusV8Procedure.returnType>;
export type AdminGetFidAuthEpochArgs = __Infer<typeof AdminGetFidAuthEpochProcedure.params>;
export type AdminGetFidAuthEpochResult = __Infer<typeof AdminGetFidAuthEpochProcedure.returnType>;
export type AdminGetSnapScanBatchAggregateV1Args = __Infer<typeof AdminGetSnapScanBatchAggregateV1Procedure.params>;
export type AdminGetSnapScanBatchAggregateV1Result = __Infer<typeof AdminGetSnapScanBatchAggregateV1Procedure.returnType>;
export type AdminInspectGenesisWaterLayoutV1Args = __Infer<typeof AdminInspectGenesisWaterLayoutV1Procedure.params>;
export type AdminInspectGenesisWaterLayoutV1Result = __Infer<typeof AdminInspectGenesisWaterLayoutV1Procedure.returnType>;
export type AuthResolverGetFidAdmissionV2Args = __Infer<typeof AuthResolverGetFidAdmissionV2Procedure.params>;
export type AuthResolverGetFidAdmissionV2Result = __Infer<typeof AuthResolverGetFidAdmissionV2Procedure.returnType>;
export type GetAlphaBackendInfoArgs = __Infer<typeof GetAlphaBackendInfoProcedure.params>;
export type GetAlphaBackendInfoResult = __Infer<typeof GetAlphaBackendInfoProcedure.returnType>;
export type GetMyAdmissionStatusArgs = __Infer<typeof GetMyAdmissionStatusProcedure.params>;
export type GetMyAdmissionStatusResult = __Infer<typeof GetMyAdmissionStatusProcedure.returnType>;
export type GetMyAdmissionStatusV2Args = __Infer<typeof GetMyAdmissionStatusV2Procedure.params>;
export type GetMyAdmissionStatusV2Result = __Infer<typeof GetMyAdmissionStatusV2Procedure.returnType>;
export type GetMyFoodExpeditionStateV1Args = __Infer<typeof GetMyFoodExpeditionStateV1Procedure.params>;
export type GetMyFoodExpeditionStateV1Result = __Infer<typeof GetMyFoodExpeditionStateV1Procedure.returnType>;
export type GetMyGoldExpeditionStateV1Args = __Infer<typeof GetMyGoldExpeditionStateV1Procedure.params>;
export type GetMyGoldExpeditionStateV1Result = __Infer<typeof GetMyGoldExpeditionStateV1Procedure.returnType>;
export type GetMyResourceStateV1Args = __Infer<typeof GetMyResourceStateV1Procedure.params>;
export type GetMyResourceStateV1Result = __Infer<typeof GetMyResourceStateV1Procedure.returnType>;
export type GetMyWoodExpeditionStateV1Args = __Infer<typeof GetMyWoodExpeditionStateV1Procedure.params>;
export type GetMyWoodExpeditionStateV1Result = __Infer<typeof GetMyWoodExpeditionStateV1Procedure.returnType>;
export type QaObserverGetRealmAttestationV2Args = __Infer<typeof QaObserverGetRealmAttestationV2Procedure.params>;
export type QaObserverGetRealmAttestationV2Result = __Infer<typeof QaObserverGetRealmAttestationV2Procedure.returnType>;
export type QaObserverGetRealmSnapshotV1Args = __Infer<typeof QaObserverGetRealmSnapshotV1Procedure.params>;
export type QaObserverGetRealmSnapshotV1Result = __Infer<typeof QaObserverGetRealmSnapshotV1Procedure.returnType>;

