// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminAllowFidReducer from "../admin_allow_fid_reducer";
import AdminBumpAuthEpochReducer from "../admin_bump_auth_epoch_reducer";
import AdminDisableFidReducer from "../admin_disable_fid_reducer";
import AdminSeedWorldReducer from "../admin_seed_world_reducer";
import BootstrapPlayerReducer from "../bootstrap_player_reducer";

export type AdminAllowFidParams = __Infer<typeof AdminAllowFidReducer>;
export type AdminBumpAuthEpochParams = __Infer<typeof AdminBumpAuthEpochReducer>;
export type AdminDisableFidParams = __Infer<typeof AdminDisableFidReducer>;
export type AdminSeedWorldParams = __Infer<typeof AdminSeedWorldReducer>;
export type BootstrapPlayerParams = __Infer<typeof BootstrapPlayerReducer>;

