// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptAlphaTermsV1Reducer from "../accept_alpha_terms_v_1_reducer";
import AdminActivateGenesisWaterLayoutV1Reducer from "../admin_activate_genesis_water_layout_v_1_reducer";
import AdminActivateGenesisWaterRevisionV1Reducer from "../admin_activate_genesis_water_revision_v_1_reducer";
import AdminAdmitFounderV1Reducer from "../admin_admit_founder_v_1_reducer";
import AdminAllowFidReducer from "../admin_allow_fid_reducer";
import AdminBackfillResourceAccountsV1Reducer from "../admin_backfill_resource_accounts_v_1_reducer";
import AdminBeginSnapScanBatchV1Reducer from "../admin_begin_snap_scan_batch_v_1_reducer";
import AdminBumpAuthEpochReducer from "../admin_bump_auth_epoch_reducer";
import AdminCreditSnapBurnV1Reducer from "../admin_credit_snap_burn_v_1_reducer";
import AdminDisableFidReducer from "../admin_disable_fid_reducer";
import AdminExpandGenesisWorldV3Reducer from "../admin_expand_genesis_world_v_3_reducer";
import AdminFinalizeSnapScanBatchV1Reducer from "../admin_finalize_snap_scan_batch_v_1_reducer";
import AdminReplaceFidWalletSnapshotV1Reducer from "../admin_replace_fid_wallet_snapshot_v_1_reducer";
import AdminSeedGenesisForestLayoutV1Reducer from "../admin_seed_genesis_forest_layout_v_1_reducer";
import AdminSeedGenesisTierIFoodSitesV1Reducer from "../admin_seed_genesis_tier_i_food_sites_v_1_reducer";
import AdminSeedGenesisTierIGoldSitesV1Reducer from "../admin_seed_genesis_tier_i_gold_sites_v_1_reducer";
import AdminSeedGenesisTierIStoneSitesV1Reducer from "../admin_seed_genesis_tier_i_stone_sites_v_1_reducer";
import AdminSeedGenesisTierIWoodSitesV1Reducer from "../admin_seed_genesis_tier_i_wood_sites_v_1_reducer";
import AdminSeedGenesisWaterLayoutV1Reducer from "../admin_seed_genesis_water_layout_v_1_reducer";
import AdminSeedGenesisWaterRevisionV1Reducer from "../admin_seed_genesis_water_revision_v_1_reducer";
import AdminSeedWorldReducer from "../admin_seed_world_reducer";
import AdminUpsertFidWalletAttributionV1Reducer from "../admin_upsert_fid_wallet_attribution_v_1_reducer";
import AdminUpsertRealmProfileV1Reducer from "../admin_upsert_realm_profile_v_1_reducer";
import BootstrapPlayerReducer from "../bootstrap_player_reducer";
import BootstrapPlayerV2Reducer from "../bootstrap_player_v_2_reducer";
import CollectFoodExpeditionV1Reducer from "../collect_food_expedition_v_1_reducer";
import CollectGoldExpeditionV1Reducer from "../collect_gold_expedition_v_1_reducer";
import CollectResourcesV1Reducer from "../collect_resources_v_1_reducer";
import CollectStoneExpeditionV1Reducer from "../collect_stone_expedition_v_1_reducer";
import CollectWoodExpeditionV1Reducer from "../collect_wood_expedition_v_1_reducer";
import DispatchFoodExpeditionV1Reducer from "../dispatch_food_expedition_v_1_reducer";
import DispatchGoldExpeditionV1Reducer from "../dispatch_gold_expedition_v_1_reducer";
import DispatchStoneExpeditionV1Reducer from "../dispatch_stone_expedition_v_1_reducer";
import DispatchWoodExpeditionV1Reducer from "../dispatch_wood_expedition_v_1_reducer";
import DispatchWorkerV1Reducer from "../dispatch_worker_v_1_reducer";
import RecallAllWorkersV1Reducer from "../recall_all_workers_v_1_reducer";
import RecallWorkerV1Reducer from "../recall_worker_v_1_reducer";

export type AcceptAlphaTermsV1Params = __Infer<typeof AcceptAlphaTermsV1Reducer>;
export type AdminActivateGenesisWaterLayoutV1Params = __Infer<typeof AdminActivateGenesisWaterLayoutV1Reducer>;
export type AdminActivateGenesisWaterRevisionV1Params = __Infer<typeof AdminActivateGenesisWaterRevisionV1Reducer>;
export type AdminAdmitFounderV1Params = __Infer<typeof AdminAdmitFounderV1Reducer>;
export type AdminAllowFidParams = __Infer<typeof AdminAllowFidReducer>;
export type AdminBackfillResourceAccountsV1Params = __Infer<typeof AdminBackfillResourceAccountsV1Reducer>;
export type AdminBeginSnapScanBatchV1Params = __Infer<typeof AdminBeginSnapScanBatchV1Reducer>;
export type AdminBumpAuthEpochParams = __Infer<typeof AdminBumpAuthEpochReducer>;
export type AdminCreditSnapBurnV1Params = __Infer<typeof AdminCreditSnapBurnV1Reducer>;
export type AdminDisableFidParams = __Infer<typeof AdminDisableFidReducer>;
export type AdminExpandGenesisWorldV3Params = __Infer<typeof AdminExpandGenesisWorldV3Reducer>;
export type AdminFinalizeSnapScanBatchV1Params = __Infer<typeof AdminFinalizeSnapScanBatchV1Reducer>;
export type AdminReplaceFidWalletSnapshotV1Params = __Infer<typeof AdminReplaceFidWalletSnapshotV1Reducer>;
export type AdminSeedGenesisForestLayoutV1Params = __Infer<typeof AdminSeedGenesisForestLayoutV1Reducer>;
export type AdminSeedGenesisTierIFoodSitesV1Params = __Infer<typeof AdminSeedGenesisTierIFoodSitesV1Reducer>;
export type AdminSeedGenesisTierIGoldSitesV1Params = __Infer<typeof AdminSeedGenesisTierIGoldSitesV1Reducer>;
export type AdminSeedGenesisTierIStoneSitesV1Params = __Infer<typeof AdminSeedGenesisTierIStoneSitesV1Reducer>;
export type AdminSeedGenesisTierIWoodSitesV1Params = __Infer<typeof AdminSeedGenesisTierIWoodSitesV1Reducer>;
export type AdminSeedGenesisWaterLayoutV1Params = __Infer<typeof AdminSeedGenesisWaterLayoutV1Reducer>;
export type AdminSeedGenesisWaterRevisionV1Params = __Infer<typeof AdminSeedGenesisWaterRevisionV1Reducer>;
export type AdminSeedWorldParams = __Infer<typeof AdminSeedWorldReducer>;
export type AdminUpsertFidWalletAttributionV1Params = __Infer<typeof AdminUpsertFidWalletAttributionV1Reducer>;
export type AdminUpsertRealmProfileV1Params = __Infer<typeof AdminUpsertRealmProfileV1Reducer>;
export type BootstrapPlayerParams = __Infer<typeof BootstrapPlayerReducer>;
export type BootstrapPlayerV2Params = __Infer<typeof BootstrapPlayerV2Reducer>;
export type CollectFoodExpeditionV1Params = __Infer<typeof CollectFoodExpeditionV1Reducer>;
export type CollectGoldExpeditionV1Params = __Infer<typeof CollectGoldExpeditionV1Reducer>;
export type CollectResourcesV1Params = __Infer<typeof CollectResourcesV1Reducer>;
export type CollectStoneExpeditionV1Params = __Infer<typeof CollectStoneExpeditionV1Reducer>;
export type CollectWoodExpeditionV1Params = __Infer<typeof CollectWoodExpeditionV1Reducer>;
export type DispatchFoodExpeditionV1Params = __Infer<typeof DispatchFoodExpeditionV1Reducer>;
export type DispatchGoldExpeditionV1Params = __Infer<typeof DispatchGoldExpeditionV1Reducer>;
export type DispatchStoneExpeditionV1Params = __Infer<typeof DispatchStoneExpeditionV1Reducer>;
export type DispatchWoodExpeditionV1Params = __Infer<typeof DispatchWoodExpeditionV1Reducer>;
export type DispatchWorkerV1Params = __Infer<typeof DispatchWorkerV1Reducer>;
export type RecallAllWorkersV1Params = __Infer<typeof RecallAllWorkersV1Reducer>;
export type RecallWorkerV1Params = __Infer<typeof RecallWorkerV1Reducer>;

