/**
 * Exact, audited candidate-geography exhaustion outcomes.
 *
 * These codes mean a deterministic seed exhausted a bounded placement search
 * or cannot reconcile its otherwise valid geography with an immutable atlas
 * constraint; the batch generator may record the attempt and continue with
 * the next ordinal. Invariants, malformed input, toolchain, filesystem, and
 * package failures must remain ordinary fatal errors and are intentionally
 * absent.
 */
export const GREATER_REALM_CANDIDATE_REJECTION_CODES = Object.freeze([
  'GREATER_REALM_TECTONIC_DOMAIN_PLACEMENT_FAILED',
  'GREATER_REALM_ISLAND_ARC_PLACEMENT_FAILED',
  'GREATER_REALM_ACTIVE_MASK_EMPTY',
  'GREATER_REALM_ACTIVE_GRID_CELL_COUNT_OUT_OF_RANGE',
  'GREATER_REALM_LEGACY_LOWLANDS_PLACEMENT_MISSING',
  'GREATER_REALM_LEGACY_LOWLANDS_PLACEMENT_FAILED',
  'GREATER_REALM_OCEAN_OUTLETS_MISSING',
  'GREATER_REALM_RECONCILED_OCEAN_OUTLETS_MISSING',
  'GREATER_REALM_LEGACY_LOWLANDS_RESERVE_TOO_LARGE',
  'GREATER_REALM_STRATEGIC_BASIN_CAPACITY_INVARIANT',
  'GREATER_REALM_TIER_THREE_CAPACITY_INVARIANT',
  // Historical `.17` checkpoints may contain this collapsed outcome. The
  // `.18` generator keeps it parseable for authenticated retirement only and
  // emits one of the typed Tier-II outcomes declared below instead.
  'GREATER_REALM_TIER_TWO_CAPACITY_INVARIANT',
  'GREATER_REALM_TIER_TWO_PASSABLE_COMPONENTS_EMPTY',
  'GREATER_REALM_TIER_TWO_STRATEGIC_COMPONENTS_EMPTY',
  'GREATER_REALM_TIER_TWO_GATE_PARENT_SLOT_MISSING',
  'GREATER_REALM_TIER_TWO_ASSIGNMENT_MISSING',
  'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_NO_MATCH',
  'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_SEARCH_NODE_LIMIT',
  'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_COMPLETE_PLAN_LIMIT',
  'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_PLAN_MISSING',
  'GREATER_REALM_TIER_TWO_STRATEGIC_AUTHORITY_SEED_INVALID',
  'GREATER_REALM_TIER_TWO_SPINE_CAPACITY_EXCEEDED',
  'GREATER_REALM_TIER_TWO_SPINE_OVERLAP',
  'GREATER_REALM_TIER_TWO_SPINE_OWNER_CONFLICT',
  'GREATER_REALM_TIER_TWO_DESIRED_CAPACITY_INVALID',
  'GREATER_REALM_TIER_TWO_PRIMARY_COMPONENT_UNDERSIZED',
  'GREATER_REALM_TIER_TWO_DESIRED_CAPACITY_UNDERSIZED',
  'GREATER_REALM_TIER_TWO_PASSABLE_OWNER_INVALID',
  'GREATER_REALM_TIER_TWO_PROMOTION_CAPACITY_MISSING',
  'GREATER_REALM_TIER_TWO_NON_PASSABLE_ASSIGNMENT_EXHAUSTED',
  'GREATER_REALM_TIER_TWO_LOWLANDS_DEMOTION_FORBIDDEN',
  'GREATER_REALM_TIER_TWO_NON_PASSABLE_DEFICIT_REMAINS',
  'GREATER_REALM_TIER_TWO_NON_PASSABLE_BALANCE_INVALID',
  'GREATER_REALM_TIER_TWO_TIER_TOTAL_CHANGED',
  'GREATER_REALM_TIER_TWO_REGION_TOTAL_CHANGED',
  'GREATER_REALM_TIER_TWO_REGION_CELL_CAPACITY_EXCEEDED',
  'GREATER_REALM_TIER_TWO_REGION_BALANCE_FAILED',
  'GREATER_REALM_TIER_TWO_LOWLANDS_LOCK_CHANGED',
  'GREATER_REALM_TIER_TWO_STRATEGIC_AUTHORITY_OWNERSHIP_CHANGED',
  'GREATER_REALM_TIER_TWO_PASSABLE_COHERENCE_FAILED',
  'GREATER_REALM_TIER_TWO_STRATEGIC_FRONTIER_MISSING',
  'GREATER_REALM_TIER_TWO_BOUNDARY_MISSING',
  'GREATER_REALM_TIER_TWO_THRONE_COMPONENT_REPAIR_FORBIDDEN',
  'GREATER_REALM_TIER_TWO_AUTHORITY_SHAPE_INVALID',
  'GREATER_REALM_TIER_TWO_AUTHORITY_PASSABLE_OWNERSHIP_INVALID',
  'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_OWNERSHIP_INVALID',
  'GREATER_REALM_TIER_TWO_AUTHORITY_BARRIER_FRONTIER_INVALID',
  'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_FRONTIER_INVALID',
  'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_CONNECTIVITY_INVALID',
  'GREATER_REALM_TIER_TWO_LEGACY_PROTECTED_AUTHORITY_CHANGED',
  'GREATER_REALM_TIER_TWO_FINAL_AUTHORITY_COUNTS_CHANGED',
  'GREATER_REALM_STRATEGIC_HIGHLAND_REFERENCE_MISSING',
  'GREATER_REALM_HYDROLOGY_BODY_SURFACE_GEOGRAPHY_EXHAUSTED',
] as const);

export type GreaterRealmCandidateRejectionCode =
  typeof GREATER_REALM_CANDIDATE_REJECTION_CODES[number];

export const GREATER_REALM_TIER_TWO_CAPACITY_REJECTION_REASONS = Object.freeze([
  'PASSABLE_COMPONENTS_EMPTY',
  'STRATEGIC_COMPONENTS_EMPTY',
  'GATE_PARENT_SLOT_MISSING',
  'ASSIGNMENT_MISSING',
  'DRY_GATE_APRON_NO_MATCH',
  'DRY_GATE_APRON_SEARCH_NODE_LIMIT',
  'DRY_GATE_APRON_COMPLETE_PLAN_LIMIT',
  'DRY_GATE_APRON_PLAN_MISSING',
  'STRATEGIC_AUTHORITY_SEED_INVALID',
  'SPINE_CAPACITY_EXCEEDED',
  'SPINE_OVERLAP',
  'SPINE_OWNER_CONFLICT',
  'DESIRED_CAPACITY_INVALID',
  'PRIMARY_COMPONENT_UNDERSIZED',
  'DESIRED_CAPACITY_UNDERSIZED',
  'PASSABLE_OWNER_INVALID',
  'PROMOTION_CAPACITY_MISSING',
  'NON_PASSABLE_ASSIGNMENT_EXHAUSTED',
  'LOWLANDS_DEMOTION_FORBIDDEN',
  'NON_PASSABLE_DEFICIT_REMAINS',
  'NON_PASSABLE_BALANCE_INVALID',
  'TIER_TOTAL_CHANGED',
  'REGION_TOTAL_CHANGED',
  'REGION_CELL_CAPACITY_EXCEEDED',
  'REGION_BALANCE_FAILED',
  'LOWLANDS_LOCK_CHANGED',
  'STRATEGIC_AUTHORITY_OWNERSHIP_CHANGED',
  'PASSABLE_COHERENCE_FAILED',
  'STRATEGIC_FRONTIER_MISSING',
  'BOUNDARY_MISSING',
  'THRONE_COMPONENT_REPAIR_FORBIDDEN',
  'AUTHORITY_SHAPE_INVALID',
  'AUTHORITY_PASSABLE_OWNERSHIP_INVALID',
  'AUTHORITY_SPINE_OWNERSHIP_INVALID',
  'AUTHORITY_BARRIER_FRONTIER_INVALID',
  'AUTHORITY_SPINE_FRONTIER_INVALID',
  'AUTHORITY_SPINE_CONNECTIVITY_INVALID',
  'LEGACY_PROTECTED_AUTHORITY_CHANGED',
  'FINAL_AUTHORITY_COUNTS_CHANGED',
] as const);

export type GreaterRealmTierTwoCapacityRejectionReason =
  typeof GREATER_REALM_TIER_TWO_CAPACITY_REJECTION_REASONS[number];

export const GREATER_REALM_TIER_TWO_CAPACITY_REJECTION_CODE_BY_REASON =
  Object.freeze({
    PASSABLE_COMPONENTS_EMPTY: 'GREATER_REALM_TIER_TWO_PASSABLE_COMPONENTS_EMPTY',
    STRATEGIC_COMPONENTS_EMPTY: 'GREATER_REALM_TIER_TWO_STRATEGIC_COMPONENTS_EMPTY',
    GATE_PARENT_SLOT_MISSING: 'GREATER_REALM_TIER_TWO_GATE_PARENT_SLOT_MISSING',
    ASSIGNMENT_MISSING: 'GREATER_REALM_TIER_TWO_ASSIGNMENT_MISSING',
    DRY_GATE_APRON_NO_MATCH: 'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_NO_MATCH',
    DRY_GATE_APRON_SEARCH_NODE_LIMIT:
      'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_SEARCH_NODE_LIMIT',
    DRY_GATE_APRON_COMPLETE_PLAN_LIMIT:
      'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_COMPLETE_PLAN_LIMIT',
    DRY_GATE_APRON_PLAN_MISSING: 'GREATER_REALM_TIER_TWO_DRY_GATE_APRON_PLAN_MISSING',
    STRATEGIC_AUTHORITY_SEED_INVALID:
      'GREATER_REALM_TIER_TWO_STRATEGIC_AUTHORITY_SEED_INVALID',
    SPINE_CAPACITY_EXCEEDED: 'GREATER_REALM_TIER_TWO_SPINE_CAPACITY_EXCEEDED',
    SPINE_OVERLAP: 'GREATER_REALM_TIER_TWO_SPINE_OVERLAP',
    SPINE_OWNER_CONFLICT: 'GREATER_REALM_TIER_TWO_SPINE_OWNER_CONFLICT',
    DESIRED_CAPACITY_INVALID: 'GREATER_REALM_TIER_TWO_DESIRED_CAPACITY_INVALID',
    PRIMARY_COMPONENT_UNDERSIZED:
      'GREATER_REALM_TIER_TWO_PRIMARY_COMPONENT_UNDERSIZED',
    DESIRED_CAPACITY_UNDERSIZED:
      'GREATER_REALM_TIER_TWO_DESIRED_CAPACITY_UNDERSIZED',
    PASSABLE_OWNER_INVALID: 'GREATER_REALM_TIER_TWO_PASSABLE_OWNER_INVALID',
    PROMOTION_CAPACITY_MISSING: 'GREATER_REALM_TIER_TWO_PROMOTION_CAPACITY_MISSING',
    NON_PASSABLE_ASSIGNMENT_EXHAUSTED:
      'GREATER_REALM_TIER_TWO_NON_PASSABLE_ASSIGNMENT_EXHAUSTED',
    LOWLANDS_DEMOTION_FORBIDDEN:
      'GREATER_REALM_TIER_TWO_LOWLANDS_DEMOTION_FORBIDDEN',
    NON_PASSABLE_DEFICIT_REMAINS:
      'GREATER_REALM_TIER_TWO_NON_PASSABLE_DEFICIT_REMAINS',
    NON_PASSABLE_BALANCE_INVALID:
      'GREATER_REALM_TIER_TWO_NON_PASSABLE_BALANCE_INVALID',
    TIER_TOTAL_CHANGED: 'GREATER_REALM_TIER_TWO_TIER_TOTAL_CHANGED',
    REGION_TOTAL_CHANGED: 'GREATER_REALM_TIER_TWO_REGION_TOTAL_CHANGED',
    REGION_CELL_CAPACITY_EXCEEDED:
      'GREATER_REALM_TIER_TWO_REGION_CELL_CAPACITY_EXCEEDED',
    REGION_BALANCE_FAILED: 'GREATER_REALM_TIER_TWO_REGION_BALANCE_FAILED',
    LOWLANDS_LOCK_CHANGED: 'GREATER_REALM_TIER_TWO_LOWLANDS_LOCK_CHANGED',
    STRATEGIC_AUTHORITY_OWNERSHIP_CHANGED:
      'GREATER_REALM_TIER_TWO_STRATEGIC_AUTHORITY_OWNERSHIP_CHANGED',
    PASSABLE_COHERENCE_FAILED:
      'GREATER_REALM_TIER_TWO_PASSABLE_COHERENCE_FAILED',
    STRATEGIC_FRONTIER_MISSING:
      'GREATER_REALM_TIER_TWO_STRATEGIC_FRONTIER_MISSING',
    BOUNDARY_MISSING: 'GREATER_REALM_TIER_TWO_BOUNDARY_MISSING',
    THRONE_COMPONENT_REPAIR_FORBIDDEN:
      'GREATER_REALM_TIER_TWO_THRONE_COMPONENT_REPAIR_FORBIDDEN',
    AUTHORITY_SHAPE_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_SHAPE_INVALID',
    AUTHORITY_PASSABLE_OWNERSHIP_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_PASSABLE_OWNERSHIP_INVALID',
    AUTHORITY_SPINE_OWNERSHIP_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_OWNERSHIP_INVALID',
    AUTHORITY_BARRIER_FRONTIER_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_BARRIER_FRONTIER_INVALID',
    AUTHORITY_SPINE_FRONTIER_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_FRONTIER_INVALID',
    AUTHORITY_SPINE_CONNECTIVITY_INVALID:
      'GREATER_REALM_TIER_TWO_AUTHORITY_SPINE_CONNECTIVITY_INVALID',
    LEGACY_PROTECTED_AUTHORITY_CHANGED:
      'GREATER_REALM_TIER_TWO_LEGACY_PROTECTED_AUTHORITY_CHANGED',
    FINAL_AUTHORITY_COUNTS_CHANGED:
      'GREATER_REALM_TIER_TWO_FINAL_AUTHORITY_COUNTS_CHANGED',
  } as const satisfies Record<
    GreaterRealmTierTwoCapacityRejectionReason,
    GreaterRealmCandidateRejectionCode
  >);

const CANDIDATE_REJECTION_CODE_SET: ReadonlySet<string> = new Set(
  GREATER_REALM_CANDIDATE_REJECTION_CODES,
);

export class GreaterRealmCandidateRejectionError extends Error {
  readonly code: GreaterRealmCandidateRejectionCode;

  constructor(code: GreaterRealmCandidateRejectionCode) {
    super(code);
    if (!CANDIDATE_REJECTION_CODE_SET.has(code)) {
      throw new Error('GREATER_REALM_CANDIDATE_REJECTION_CODE_INVALID');
    }
    this.name = 'GreaterRealmCandidateRejectionError';
    this.code = code;
  }
}

export function rejectGreaterRealmCandidate(
  code: GreaterRealmCandidateRejectionCode,
): never {
  throw new GreaterRealmCandidateRejectionError(code);
}

export function rejectGreaterRealmTierTwoCapacity(
  reason: GreaterRealmTierTwoCapacityRejectionReason,
): never {
  return rejectGreaterRealmCandidate(
    GREATER_REALM_TIER_TWO_CAPACITY_REJECTION_CODE_BY_REASON[reason],
  );
}

/** Never classify an ordinary Error merely because its message matches. */
export function greaterRealmCandidateRejectionCode(
  error: unknown,
): GreaterRealmCandidateRejectionCode | undefined {
  return error instanceof GreaterRealmCandidateRejectionError
    ? error.code
    : undefined;
}
