// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptAlphaTermsV1Reducer from "../accept_alpha_terms_v_1_reducer";
import AdminAdmitFounderForAccessRequestV2Reducer from "../admin_admit_founder_for_access_request_v_2_reducer";
import AdminAdmitFounderV1Reducer from "../admin_admit_founder_v_1_reducer";
import AdminAllowFidReducer from "../admin_allow_fid_reducer";
import AdminAllowFidForAccessRequestV1Reducer from "../admin_allow_fid_for_access_request_v_1_reducer";
import AdminBeginGreaterRealmVerificationV1Reducer from "../admin_begin_greater_realm_verification_v_1_reducer";
import AdminBumpAuthEpochReducer from "../admin_bump_auth_epoch_reducer";
import AdminDisableFidReducer from "../admin_disable_fid_reducer";
import AdminFinalizeGreaterRealmReleaseV1Reducer from "../admin_finalize_greater_realm_release_v_1_reducer";
import AdminImportGreaterRealmChunkV1Reducer from "../admin_import_greater_realm_chunk_v_1_reducer";
import AdminImportGreaterRealmComponentsV1Reducer from "../admin_import_greater_realm_components_v_1_reducer";
import AdminImportGreaterRealmRegionsV1Reducer from "../admin_import_greater_realm_regions_v_1_reducer";
import AdminResetAccessRequestV1Reducer from "../admin_reset_access_request_v_1_reducer";
import AdminStageGreaterRealmReleaseV1Reducer from "../admin_stage_greater_realm_release_v_1_reducer";
import AdminUpsertRealmProfileV1Reducer from "../admin_upsert_realm_profile_v_1_reducer";
import AdminVerifyGreaterRealmBatchV1Reducer from "../admin_verify_greater_realm_batch_v_1_reducer";
import BootstrapPlayerReducer from "../bootstrap_player_reducer";
import BootstrapPlayerV2Reducer from "../bootstrap_player_v_2_reducer";
import OnConnectReducer from "../on_connect_reducer";

export type AcceptAlphaTermsV1Params = __Infer<typeof AcceptAlphaTermsV1Reducer>;
export type AdminAdmitFounderForAccessRequestV2Params = __Infer<typeof AdminAdmitFounderForAccessRequestV2Reducer>;
export type AdminAdmitFounderV1Params = __Infer<typeof AdminAdmitFounderV1Reducer>;
export type AdminAllowFidParams = __Infer<typeof AdminAllowFidReducer>;
export type AdminAllowFidForAccessRequestV1Params = __Infer<typeof AdminAllowFidForAccessRequestV1Reducer>;
export type AdminBeginGreaterRealmVerificationV1Params = __Infer<typeof AdminBeginGreaterRealmVerificationV1Reducer>;
export type AdminBumpAuthEpochParams = __Infer<typeof AdminBumpAuthEpochReducer>;
export type AdminDisableFidParams = __Infer<typeof AdminDisableFidReducer>;
export type AdminFinalizeGreaterRealmReleaseV1Params = __Infer<typeof AdminFinalizeGreaterRealmReleaseV1Reducer>;
export type AdminImportGreaterRealmChunkV1Params = __Infer<typeof AdminImportGreaterRealmChunkV1Reducer>;
export type AdminImportGreaterRealmComponentsV1Params = __Infer<typeof AdminImportGreaterRealmComponentsV1Reducer>;
export type AdminImportGreaterRealmRegionsV1Params = __Infer<typeof AdminImportGreaterRealmRegionsV1Reducer>;
export type AdminResetAccessRequestV1Params = __Infer<typeof AdminResetAccessRequestV1Reducer>;
export type AdminStageGreaterRealmReleaseV1Params = __Infer<typeof AdminStageGreaterRealmReleaseV1Reducer>;
export type AdminUpsertRealmProfileV1Params = __Infer<typeof AdminUpsertRealmProfileV1Reducer>;
export type AdminVerifyGreaterRealmBatchV1Params = __Infer<typeof AdminVerifyGreaterRealmBatchV1Reducer>;
export type BootstrapPlayerParams = __Infer<typeof BootstrapPlayerReducer>;
export type BootstrapPlayerV2Params = __Infer<typeof BootstrapPlayerV2Reducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
