// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  batchId: __t.string(),
  eventKey: __t.string(),
  chainId: __t.u32(),
  tokenContract: __t.string(),
  transactionHash: __t.string(),
  logIndex: __t.u32(),
  burnReference: __t.string(),
  burnMethod: __t.string(),
  senderAddress: __t.string(),
  blockNumber: __t.u64(),
  blockHash: __t.string(),
  amountMicros: __t.u128(),
  attributedFid: __t.u64(),
  attributionPolicyVersion: __t.string(),
  implementationAddress: __t.string(),
  contractCodeHash: __t.string(),
};
