// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  capability: __t.string(),
  sourceCommit: __t.string(),
  moduleArtifactDigest: __t.string(),
  expectedCastleCount: __t.u32(),
  expectedWorkerCount: __t.u32(),
  rosterDigest: __t.string(),
  resourceRosterDigest: __t.string(),
  resourceCatalogDigest: __t.string(),
  goldExpeditions: __t.u32(),
  foodExpeditions: __t.u32(),
  woodExpeditions: __t.u32(),
  stoneExpeditions: __t.u32(),
  goldOccupations: __t.u32(),
  foodOccupations: __t.u32(),
  woodOccupations: __t.u32(),
  stoneOccupations: __t.u32(),
  goldSchedules: __t.u32(),
  foodSchedules: __t.u32(),
  woodSchedules: __t.u32(),
  stoneSchedules: __t.u32(),
};
