// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  batchId: __t.string(),
  previousFinalizedBlock: __t.u64(),
  previousFinalizedBlockHash: __t.string(),
  throughFinalizedBlock: __t.u64(),
  throughFinalizedBlockHash: __t.string(),
  walletSnapshotGeneration: __t.u64(),
  walletSnapshotId: __t.string(),
  expectedCredits: __t.u32(),
  expectedMicros: __t.u128(),
  proxyCodeHash: __t.string(),
  implementationAddress: __t.string(),
  implementationCodeHash: __t.string(),
};
