// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  ProductionPlayerCanaryAdminEvidenceV1,
} from "./types";

export const params = {
  fid: __t.u64(),
  reviewedAdmissionPlanDigest: __t.string(),
  evidenceNonce: __t.string(),
  dispatchIdempotencyKeys: __t.array(__t.string()),
  recallIdempotencyKeys: __t.array(__t.string()),
};
export const returnType = ProductionPlayerCanaryAdminEvidenceV1