// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  capability: __t.string(),
  clientRelease: __t.string(),
  clientArtifactDigest: __t.string(),
  sourceCommit: __t.string(),
  resourceStateVersion: __t.u32(),
  resourcePolicyVersion: __t.string(),
  resourceCatalogDigest: __t.string(),
  expectedCastleCount: __t.u32(),
  expectedWorkerCount: __t.u32(),
  rosterDigest: __t.string(),
  resourceRosterDigest: __t.string(),
};
