// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  capability: __t.string(),
  policyDigest: __t.string(),
  layoutDigest: __t.string(),
  assetCatalogDigest: __t.string(),
  expectedCastles: __t.u32(),
  expectedExistingBuilders: __t.u32(),
  expectedMissingBuilders: __t.u32(),
};
