// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slotId: __t.u32().primaryKey().name("slot_id"),
  realmId: __t.string().name("realm_id"),
  tileKey: __t.string().name("tile_key"),
  q: __t.i32(),
  r: __t.i32(),
  generationVersion: __t.u32().name("generation_version"),
});
