// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workerId: __t.string().primaryKey().name("worker_id"),
  originCastleId: __t.u64().name("origin_castle_id"),
  ordinal: __t.u32(),
  status: __t.string(),
  resourceKind: __t.option(__t.string()).name("resource_kind"),
  siteId: __t.option(__t.string()).name("site_id"),
  startedAtMicros: __t.option(__t.u64()).name("started_at_micros"),
  arrivesAtMicros: __t.option(__t.u64()).name("arrives_at_micros"),
  gatheringEndsAtMicros: __t.option(__t.u64()).name("gathering_ends_at_micros"),
  returnStartedAtMicros: __t.option(__t.u64()).name("return_started_at_micros"),
  returnsAtMicros: __t.option(__t.u64()).name("returns_at_micros"),
  routeSteps: __t.option(__t.u32()).name("route_steps"),
  returnStartProgressBasisPoints: __t.option(__t.u32()).name("return_start_progress_basis_points"),
  timelineRevision: __t.u32().name("timeline_revision"),
  revision: __t.u64(),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
