// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  buildingKey: __t.string().primaryKey().name("building_key"),
  castleId: __t.u64().name("castle_id"),
  buildingKind: __t.string().name("building_kind"),
  localXMicrounits: __t.i64().name("local_x_microunits"),
  localZMicrounits: __t.i64().name("local_z_microunits"),
  rotationMilliDegrees: __t.u32().name("rotation_milli_degrees"),
  completedLevel: __t.u32().name("completed_level"),
  targetLevel: __t.u32().name("target_level"),
  phase: __t.string(),
  startedAtMicros: __t.u64().name("started_at_micros"),
  completesAtMicros: __t.u64().name("completes_at_micros"),
  revision: __t.u64(),
  policyVersion: __t.string().name("policy_version"),
});
