// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptAlphaTermsV1Reducer from "./accept_alpha_terms_v_1_reducer";
import AdminActivateGenesisWaterLayoutV1Reducer from "./admin_activate_genesis_water_layout_v_1_reducer";
import AdminAdmitFounderV1Reducer from "./admin_admit_founder_v_1_reducer";
import AdminAllowFidReducer from "./admin_allow_fid_reducer";
import AdminBackfillResourceAccountsV1Reducer from "./admin_backfill_resource_accounts_v_1_reducer";
import AdminBeginSnapScanBatchV1Reducer from "./admin_begin_snap_scan_batch_v_1_reducer";
import AdminBumpAuthEpochReducer from "./admin_bump_auth_epoch_reducer";
import AdminCreditSnapBurnV1Reducer from "./admin_credit_snap_burn_v_1_reducer";
import AdminDisableFidReducer from "./admin_disable_fid_reducer";
import AdminExpandGenesisWorldV3Reducer from "./admin_expand_genesis_world_v_3_reducer";
import AdminFinalizeSnapScanBatchV1Reducer from "./admin_finalize_snap_scan_batch_v_1_reducer";
import AdminReplaceFidWalletSnapshotV1Reducer from "./admin_replace_fid_wallet_snapshot_v_1_reducer";
import AdminSeedGenesisForestLayoutV1Reducer from "./admin_seed_genesis_forest_layout_v_1_reducer";
import AdminSeedGenesisTierIFoodSitesV1Reducer from "./admin_seed_genesis_tier_i_food_sites_v_1_reducer";
import AdminSeedGenesisTierIGoldSitesV1Reducer from "./admin_seed_genesis_tier_i_gold_sites_v_1_reducer";
import AdminSeedGenesisTierIStoneSitesV1Reducer from "./admin_seed_genesis_tier_i_stone_sites_v_1_reducer";
import AdminSeedGenesisTierIWoodSitesV1Reducer from "./admin_seed_genesis_tier_i_wood_sites_v_1_reducer";
import AdminSeedGenesisWaterLayoutV1Reducer from "./admin_seed_genesis_water_layout_v_1_reducer";
import AdminSeedWorldReducer from "./admin_seed_world_reducer";
import AdminUpsertFidWalletAttributionV1Reducer from "./admin_upsert_fid_wallet_attribution_v_1_reducer";
import AdminUpsertRealmProfileV1Reducer from "./admin_upsert_realm_profile_v_1_reducer";
import BootstrapPlayerReducer from "./bootstrap_player_reducer";
import BootstrapPlayerV2Reducer from "./bootstrap_player_v_2_reducer";
import CollectFoodExpeditionV1Reducer from "./collect_food_expedition_v_1_reducer";
import CollectGoldExpeditionV1Reducer from "./collect_gold_expedition_v_1_reducer";
import CollectResourcesV1Reducer from "./collect_resources_v_1_reducer";
import CollectStoneExpeditionV1Reducer from "./collect_stone_expedition_v_1_reducer";
import CollectWoodExpeditionV1Reducer from "./collect_wood_expedition_v_1_reducer";
import DispatchFoodExpeditionV1Reducer from "./dispatch_food_expedition_v_1_reducer";
import DispatchGoldExpeditionV1Reducer from "./dispatch_gold_expedition_v_1_reducer";
import DispatchStoneExpeditionV1Reducer from "./dispatch_stone_expedition_v_1_reducer";
import DispatchWoodExpeditionV1Reducer from "./dispatch_wood_expedition_v_1_reducer";

// Import all procedure arg schemas
import * as AdminGetAlphaStatusProcedure from "./admin_get_alpha_status_procedure";
import * as AdminGetAlphaStatusV2Procedure from "./admin_get_alpha_status_v_2_procedure";
import * as AdminGetAlphaStatusV3Procedure from "./admin_get_alpha_status_v_3_procedure";
import * as AdminGetAlphaStatusV4Procedure from "./admin_get_alpha_status_v_4_procedure";
import * as AdminGetAlphaStatusV8Procedure from "./admin_get_alpha_status_v_8_procedure";
import * as AdminGetAlphaStatusV10Procedure from "./admin_get_alpha_status_v_10_procedure";
import * as AdminGetFidAuthEpochProcedure from "./admin_get_fid_auth_epoch_procedure";
import * as AdminGetSnapScanBatchAggregateV1Procedure from "./admin_get_snap_scan_batch_aggregate_v_1_procedure";
import * as AdminInspectGenesisWaterLayoutV1Procedure from "./admin_inspect_genesis_water_layout_v_1_procedure";
import * as AuthResolverGetFidAdmissionV2Procedure from "./auth_resolver_get_fid_admission_v_2_procedure";
import * as GetAlphaBackendInfoProcedure from "./get_alpha_backend_info_procedure";
import * as GetMyAdmissionStatusProcedure from "./get_my_admission_status_procedure";
import * as GetMyAdmissionStatusV2Procedure from "./get_my_admission_status_v_2_procedure";
import * as GetMyFoodExpeditionStateV1Procedure from "./get_my_food_expedition_state_v_1_procedure";
import * as GetMyGoldExpeditionStateV1Procedure from "./get_my_gold_expedition_state_v_1_procedure";
import * as GetMyResourceStateV1Procedure from "./get_my_resource_state_v_1_procedure";
import * as GetMyStoneExpeditionStateV1Procedure from "./get_my_stone_expedition_state_v_1_procedure";
import * as GetMyWoodExpeditionStateV1Procedure from "./get_my_wood_expedition_state_v_1_procedure";
import * as QaObserverGetRealmAttestationV2Procedure from "./qa_observer_get_realm_attestation_v_2_procedure";
import * as QaObserverGetRealmSnapshotV1Procedure from "./qa_observer_get_realm_snapshot_v_1_procedure";

// Import all table schema definitions
import CastleRow from "./castle_table";
import CastleSlotV1Row from "./castle_slot_v_1_table";
import FoodExpeditionScheduleV1Row from "./food_expedition_schedule_v_1_table";
import FoodNodeOccupationV1Row from "./food_node_occupation_v_1_table";
import FoodSiteV1Row from "./food_site_v_1_table";
import GoldExpeditionScheduleV1Row from "./gold_expedition_schedule_v_1_table";
import GoldNodeOccupationV1Row from "./gold_node_occupation_v_1_table";
import GoldSiteV1Row from "./gold_site_v_1_table";
import PlayerRow from "./player_table";
import PlayerV2Row from "./player_v_2_table";
import RealmEnvironmentV1Row from "./realm_environment_v_1_table";
import RealmForestInstanceV1Row from "./realm_forest_instance_v_1_table";
import RealmForestLayoutV1Row from "./realm_forest_layout_v_1_table";
import RealmProfileV1Row from "./realm_profile_v_1_table";
import RealmV1Row from "./realm_v_1_table";
import RealmWaterBodyV1Row from "./realm_water_body_v_1_table";
import RealmWaterCellV1Row from "./realm_water_cell_v_1_table";
import RealmWaterLayoutV1Row from "./realm_water_layout_v_1_table";
import StoneExpeditionScheduleV1Row from "./stone_expedition_schedule_v_1_table";
import StoneNodeOccupationV1Row from "./stone_node_occupation_v_1_table";
import StoneSiteV1Row from "./stone_site_v_1_table";
import WoodExpeditionScheduleV1Row from "./wood_expedition_schedule_v_1_table";
import WoodNodeOccupationV1Row from "./wood_node_occupation_v_1_table";
import WoodSiteV1Row from "./wood_site_v_1_table";
import WorldTileRow from "./world_tile_table";
import WorldTileMetaV1Row from "./world_tile_meta_v_1_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  castle: __table({
    name: 'castle',
    indexes: [
      { accessor: 'castleId', name: 'castle_castle_id_idx_btree', algorithm: 'btree', columns: [
        'castleId',
      ] },
      { accessor: 'ownerFid', name: 'castle_owner_fid_idx_btree', algorithm: 'btree', columns: [
        'ownerFid',
      ] },
      { accessor: 'tileKey', name: 'castle_tile_key_idx_btree', algorithm: 'btree', columns: [
        'tileKey',
      ] },
    ],
    constraints: [
      { name: 'castle_castle_id_key', constraint: 'unique', columns: ['castleId'] },
      { name: 'castle_owner_fid_key', constraint: 'unique', columns: ['ownerFid'] },
      { name: 'castle_tile_key_key', constraint: 'unique', columns: ['tileKey'] },
    ],
  }, CastleRow),
  castleSlotV1: __table({
    name: 'castle_slot_v1',
    indexes: [
      { accessor: 'realmId', name: 'castle_slot_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
      { accessor: 'slotId', name: 'castle_slot_v1_slot_id_idx_btree', algorithm: 'btree', columns: [
        'slotId',
      ] },
      { accessor: 'tileKey', name: 'castle_slot_v1_tile_key_idx_btree', algorithm: 'btree', columns: [
        'tileKey',
      ] },
    ],
    constraints: [
      { name: 'castle_slot_v1_slot_id_key', constraint: 'unique', columns: ['slotId'] },
      { name: 'castle_slot_v1_tile_key_key', constraint: 'unique', columns: ['tileKey'] },
    ],
  }, CastleSlotV1Row),
  foodExpeditionScheduleV1: __table({
    name: 'food_expedition_schedule_v_1',
    indexes: [
      { accessor: 'originCastleId', name: 'food_expedition_schedule_v_1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'scheduleId', name: 'food_expedition_schedule_v_1_schedule_id_idx_btree', algorithm: 'btree', columns: [
        'scheduleId',
      ] },
      { accessor: 'siteId', name: 'food_expedition_schedule_v_1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'food_expedition_schedule_v_1_schedule_id_key', constraint: 'unique', columns: ['scheduleId'] },
    ],
  }, FoodExpeditionScheduleV1Row),
  foodNodeOccupationV1: __table({
    name: 'food_node_occupation_v1',
    indexes: [
      { accessor: 'byOriginCastle', name: 'food_node_occupation_v1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'siteId', name: 'food_node_occupation_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'food_node_occupation_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, FoodNodeOccupationV1Row),
  foodSiteV1: __table({
    name: 'food_site_v1',
    indexes: [
      { accessor: 'siteId', name: 'food_site_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'food_site_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, FoodSiteV1Row),
  goldExpeditionScheduleV1: __table({
    name: 'gold_expedition_schedule_v_1',
    indexes: [
      { accessor: 'originCastleId', name: 'gold_expedition_schedule_v_1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'scheduleId', name: 'gold_expedition_schedule_v_1_schedule_id_idx_btree', algorithm: 'btree', columns: [
        'scheduleId',
      ] },
      { accessor: 'siteId', name: 'gold_expedition_schedule_v_1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'gold_expedition_schedule_v_1_schedule_id_key', constraint: 'unique', columns: ['scheduleId'] },
    ],
  }, GoldExpeditionScheduleV1Row),
  goldNodeOccupationV1: __table({
    name: 'gold_node_occupation_v1',
    indexes: [
      { accessor: 'byOriginCastle', name: 'gold_node_occupation_v1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'siteId', name: 'gold_node_occupation_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'gold_node_occupation_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, GoldNodeOccupationV1Row),
  goldSiteV1: __table({
    name: 'gold_site_v1',
    indexes: [
      { accessor: 'siteId', name: 'gold_site_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'gold_site_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, GoldSiteV1Row),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'fid', name: 'player_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_fid_key', constraint: 'unique', columns: ['fid'] },
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerV2: __table({
    name: 'player_v2',
    indexes: [
      { accessor: 'fid', name: 'player_v2_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'player_v2_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, PlayerV2Row),
  realmEnvironmentV1: __table({
    name: 'realm_environment_v1',
    indexes: [
      { accessor: 'realmId', name: 'realm_environment_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
    ],
    constraints: [
      { name: 'realm_environment_v1_realm_id_key', constraint: 'unique', columns: ['realmId'] },
    ],
  }, RealmEnvironmentV1Row),
  realmForestInstanceV1: __table({
    name: 'realm_forest_instance_v1',
    indexes: [
      { accessor: 'realmId', name: 'realm_forest_instance_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
      { accessor: 'treeId', name: 'realm_forest_instance_v1_tree_id_idx_btree', algorithm: 'btree', columns: [
        'treeId',
      ] },
    ],
    constraints: [
      { name: 'realm_forest_instance_v1_tree_id_key', constraint: 'unique', columns: ['treeId'] },
    ],
  }, RealmForestInstanceV1Row),
  realmForestLayoutV1: __table({
    name: 'realm_forest_layout_v1',
    indexes: [
      { accessor: 'realmId', name: 'realm_forest_layout_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
    ],
    constraints: [
      { name: 'realm_forest_layout_v1_realm_id_key', constraint: 'unique', columns: ['realmId'] },
    ],
  }, RealmForestLayoutV1Row),
  realmProfileV1: __table({
    name: 'realm_profile_v1',
    indexes: [
      { accessor: 'fid', name: 'realm_profile_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'realm_profile_v1_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, RealmProfileV1Row),
  realmV1: __table({
    name: 'realm_v1',
    indexes: [
      { accessor: 'realmId', name: 'realm_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
    ],
    constraints: [
      { name: 'realm_v1_realm_id_key', constraint: 'unique', columns: ['realmId'] },
    ],
  }, RealmV1Row),
  realmWaterBodyV1: __table({
    name: 'realm_water_body_v1',
    indexes: [
      { accessor: 'bodyId', name: 'realm_water_body_v1_body_id_idx_btree', algorithm: 'btree', columns: [
        'bodyId',
      ] },
      { accessor: 'realmId', name: 'realm_water_body_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
      { accessor: 'byRealmAndRegime', name: 'realm_water_body_v1_realm_id_regime_idx_btree', algorithm: 'btree', columns: [
        'realmId',
        'regime',
      ] },
    ],
    constraints: [
      { name: 'realm_water_body_v1_body_id_key', constraint: 'unique', columns: ['bodyId'] },
    ],
  }, RealmWaterBodyV1Row),
  realmWaterCellV1: __table({
    name: 'realm_water_cell_v1',
    indexes: [
      { accessor: 'byBody', name: 'realm_water_cell_v1_body_id_idx_btree', algorithm: 'btree', columns: [
        'bodyId',
      ] },
      { accessor: 'cellKey', name: 'realm_water_cell_v1_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'realmId', name: 'realm_water_cell_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
      { accessor: 'byRealmAndRegime', name: 'realm_water_cell_v1_realm_id_regime_idx_btree', algorithm: 'btree', columns: [
        'realmId',
        'regime',
      ] },
    ],
    constraints: [
      { name: 'realm_water_cell_v1_cell_key_key', constraint: 'unique', columns: ['cellKey'] },
    ],
  }, RealmWaterCellV1Row),
  realmWaterLayoutV1: __table({
    name: 'realm_water_layout_v1',
    indexes: [
      { accessor: 'realmId', name: 'realm_water_layout_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
    ],
    constraints: [
      { name: 'realm_water_layout_v1_realm_id_key', constraint: 'unique', columns: ['realmId'] },
    ],
  }, RealmWaterLayoutV1Row),
  stoneExpeditionScheduleV1: __table({
    name: 'stone_expedition_schedule_v_1',
    indexes: [
      { accessor: 'originCastleId', name: 'stone_expedition_schedule_v_1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'scheduleId', name: 'stone_expedition_schedule_v_1_schedule_id_idx_btree', algorithm: 'btree', columns: [
        'scheduleId',
      ] },
      { accessor: 'siteId', name: 'stone_expedition_schedule_v_1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'stone_expedition_schedule_v_1_schedule_id_key', constraint: 'unique', columns: ['scheduleId'] },
    ],
  }, StoneExpeditionScheduleV1Row),
  stoneNodeOccupationV1: __table({
    name: 'stone_node_occupation_v1',
    indexes: [
      { accessor: 'byOriginCastle', name: 'stone_node_occupation_v1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'siteId', name: 'stone_node_occupation_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'stone_node_occupation_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, StoneNodeOccupationV1Row),
  stoneSiteV1: __table({
    name: 'stone_site_v1',
    indexes: [
      { accessor: 'siteId', name: 'stone_site_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'stone_site_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, StoneSiteV1Row),
  woodExpeditionScheduleV1: __table({
    name: 'wood_expedition_schedule_v_1',
    indexes: [
      { accessor: 'originCastleId', name: 'wood_expedition_schedule_v_1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'scheduleId', name: 'wood_expedition_schedule_v_1_schedule_id_idx_btree', algorithm: 'btree', columns: [
        'scheduleId',
      ] },
      { accessor: 'siteId', name: 'wood_expedition_schedule_v_1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'wood_expedition_schedule_v_1_schedule_id_key', constraint: 'unique', columns: ['scheduleId'] },
    ],
  }, WoodExpeditionScheduleV1Row),
  woodNodeOccupationV1: __table({
    name: 'wood_node_occupation_v1',
    indexes: [
      { accessor: 'byOriginCastle', name: 'wood_node_occupation_v1_origin_castle_id_idx_btree', algorithm: 'btree', columns: [
        'originCastleId',
      ] },
      { accessor: 'siteId', name: 'wood_node_occupation_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'wood_node_occupation_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, WoodNodeOccupationV1Row),
  woodSiteV1: __table({
    name: 'wood_site_v1',
    indexes: [
      { accessor: 'siteId', name: 'wood_site_v1_site_id_idx_btree', algorithm: 'btree', columns: [
        'siteId',
      ] },
    ],
    constraints: [
      { name: 'wood_site_v1_site_id_key', constraint: 'unique', columns: ['siteId'] },
    ],
  }, WoodSiteV1Row),
  worldTile: __table({
    name: 'world_tile',
    indexes: [
      { accessor: 'key', name: 'world_tile_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'world_tile_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, WorldTileRow),
  worldTileMetaV1: __table({
    name: 'world_tile_meta_v1',
    indexes: [
      { accessor: 'realmId', name: 'world_tile_meta_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
      { accessor: 'byRealmAndRing', name: 'world_tile_meta_v1_realm_id_ring_idx_btree', algorithm: 'btree', columns: [
        'realmId',
        'ring',
      ] },
      { accessor: 'tileKey', name: 'world_tile_meta_v1_tile_key_idx_btree', algorithm: 'btree', columns: [
        'tileKey',
      ] },
    ],
    constraints: [
      { name: 'world_tile_meta_v1_tile_key_key', constraint: 'unique', columns: ['tileKey'] },
    ],
  }, WorldTileMetaV1Row),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_alpha_terms_v1", AcceptAlphaTermsV1Reducer),
  __reducerSchema("admin_activate_genesis_water_layout_v1", AdminActivateGenesisWaterLayoutV1Reducer),
  __reducerSchema("admin_admit_founder_v1", AdminAdmitFounderV1Reducer),
  __reducerSchema("admin_allow_fid", AdminAllowFidReducer),
  __reducerSchema("admin_backfill_resource_accounts_v1", AdminBackfillResourceAccountsV1Reducer),
  __reducerSchema("admin_begin_snap_scan_batch_v1", AdminBeginSnapScanBatchV1Reducer),
  __reducerSchema("admin_bump_auth_epoch", AdminBumpAuthEpochReducer),
  __reducerSchema("admin_credit_snap_burn_v1", AdminCreditSnapBurnV1Reducer),
  __reducerSchema("admin_disable_fid", AdminDisableFidReducer),
  __reducerSchema("admin_expand_genesis_world_v3", AdminExpandGenesisWorldV3Reducer),
  __reducerSchema("admin_finalize_snap_scan_batch_v1", AdminFinalizeSnapScanBatchV1Reducer),
  __reducerSchema("admin_replace_fid_wallet_snapshot_v1", AdminReplaceFidWalletSnapshotV1Reducer),
  __reducerSchema("admin_seed_genesis_forest_layout_v1", AdminSeedGenesisForestLayoutV1Reducer),
  __reducerSchema("admin_seed_genesis_tier_i_food_sites_v1", AdminSeedGenesisTierIFoodSitesV1Reducer),
  __reducerSchema("admin_seed_genesis_tier_i_gold_sites_v1", AdminSeedGenesisTierIGoldSitesV1Reducer),
  __reducerSchema("admin_seed_genesis_tier_i_stone_sites_v1", AdminSeedGenesisTierIStoneSitesV1Reducer),
  __reducerSchema("admin_seed_genesis_tier_i_wood_sites_v1", AdminSeedGenesisTierIWoodSitesV1Reducer),
  __reducerSchema("admin_seed_genesis_water_layout_v1", AdminSeedGenesisWaterLayoutV1Reducer),
  __reducerSchema("admin_seed_world", AdminSeedWorldReducer),
  __reducerSchema("admin_upsert_fid_wallet_attribution_v1", AdminUpsertFidWalletAttributionV1Reducer),
  __reducerSchema("admin_upsert_realm_profile_v1", AdminUpsertRealmProfileV1Reducer),
  __reducerSchema("bootstrap_player", BootstrapPlayerReducer),
  __reducerSchema("bootstrap_player_v2", BootstrapPlayerV2Reducer),
  __reducerSchema("collect_food_expedition_v1", CollectFoodExpeditionV1Reducer),
  __reducerSchema("collect_gold_expedition_v1", CollectGoldExpeditionV1Reducer),
  __reducerSchema("collect_resources_v1", CollectResourcesV1Reducer),
  __reducerSchema("collect_stone_expedition_v1", CollectStoneExpeditionV1Reducer),
  __reducerSchema("collect_wood_expedition_v1", CollectWoodExpeditionV1Reducer),
  __reducerSchema("dispatch_food_expedition_v1", DispatchFoodExpeditionV1Reducer),
  __reducerSchema("dispatch_gold_expedition_v1", DispatchGoldExpeditionV1Reducer),
  __reducerSchema("dispatch_stone_expedition_v1", DispatchStoneExpeditionV1Reducer),
  __reducerSchema("dispatch_wood_expedition_v1", DispatchWoodExpeditionV1Reducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("admin_get_alpha_status", AdminGetAlphaStatusProcedure.params, AdminGetAlphaStatusProcedure.returnType),
  __procedureSchema("admin_get_alpha_status_v2", AdminGetAlphaStatusV2Procedure.params, AdminGetAlphaStatusV2Procedure.returnType),
  __procedureSchema("admin_get_alpha_status_v3", AdminGetAlphaStatusV3Procedure.params, AdminGetAlphaStatusV3Procedure.returnType),
  __procedureSchema("admin_get_alpha_status_v4", AdminGetAlphaStatusV4Procedure.params, AdminGetAlphaStatusV4Procedure.returnType),
  __procedureSchema("admin_get_alpha_status_v8", AdminGetAlphaStatusV8Procedure.params, AdminGetAlphaStatusV8Procedure.returnType),
  __procedureSchema("admin_get_alpha_status_v_10", AdminGetAlphaStatusV10Procedure.params, AdminGetAlphaStatusV10Procedure.returnType),
  __procedureSchema("admin_get_fid_auth_epoch", AdminGetFidAuthEpochProcedure.params, AdminGetFidAuthEpochProcedure.returnType),
  __procedureSchema("admin_get_snap_scan_batch_aggregate_v1", AdminGetSnapScanBatchAggregateV1Procedure.params, AdminGetSnapScanBatchAggregateV1Procedure.returnType),
  __procedureSchema("admin_inspect_genesis_water_layout_v1", AdminInspectGenesisWaterLayoutV1Procedure.params, AdminInspectGenesisWaterLayoutV1Procedure.returnType),
  __procedureSchema("auth_resolver_get_fid_admission_v2", AuthResolverGetFidAdmissionV2Procedure.params, AuthResolverGetFidAdmissionV2Procedure.returnType),
  __procedureSchema("get_alpha_backend_info", GetAlphaBackendInfoProcedure.params, GetAlphaBackendInfoProcedure.returnType),
  __procedureSchema("get_my_admission_status", GetMyAdmissionStatusProcedure.params, GetMyAdmissionStatusProcedure.returnType),
  __procedureSchema("get_my_admission_status_v2", GetMyAdmissionStatusV2Procedure.params, GetMyAdmissionStatusV2Procedure.returnType),
  __procedureSchema("get_my_food_expedition_state_v1", GetMyFoodExpeditionStateV1Procedure.params, GetMyFoodExpeditionStateV1Procedure.returnType),
  __procedureSchema("get_my_gold_expedition_state_v1", GetMyGoldExpeditionStateV1Procedure.params, GetMyGoldExpeditionStateV1Procedure.returnType),
  __procedureSchema("get_my_resource_state_v1", GetMyResourceStateV1Procedure.params, GetMyResourceStateV1Procedure.returnType),
  __procedureSchema("get_my_stone_expedition_state_v1", GetMyStoneExpeditionStateV1Procedure.params, GetMyStoneExpeditionStateV1Procedure.returnType),
  __procedureSchema("get_my_wood_expedition_state_v1", GetMyWoodExpeditionStateV1Procedure.params, GetMyWoodExpeditionStateV1Procedure.returnType),
  __procedureSchema("qa_observer_get_realm_attestation_v2", QaObserverGetRealmAttestationV2Procedure.params, QaObserverGetRealmAttestationV2Procedure.returnType),
  __procedureSchema("qa_observer_get_realm_snapshot_v1", QaObserverGetRealmSnapshotV1Procedure.params, QaObserverGetRealmSnapshotV1Procedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

