// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  layoutId: __t.string().primaryKey().name("layout_id"),
  layoutVersion: __t.u32().name("layout_version"),
  policyVersion: __t.string().name("policy_version"),
  slotCount: __t.u32().name("slot_count"),
  mediumSlotCount: __t.u32().name("medium_slot_count"),
  largeSlotCount: __t.u32().name("large_slot_count"),
  assetCatalogDigest: __t.string().name("asset_catalog_digest"),
  layoutDigest: __t.string().name("layout_digest"),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
});
