// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  buildingKind: __t.string(),
  localXMicrounits: __t.i64(),
  localZMicrounits: __t.i64(),
  rotationMilliDegrees: __t.u32(),
  requestKey: __t.string(),
  expectedTargetLevel: __t.u32(),
  expectedProjectRevision: __t.string(),
  expectedPolicyDigest: __t.string(),
  expectedLayoutDigest: __t.string(),
};
