// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slotId: __t.string().primaryKey().name("slot_id"),
  layoutId: __t.string().name("layout_id"),
  footprintClass: __t.string().name("footprint_class"),
  localXMicrounits: __t.i64().name("local_x_microunits"),
  localZMicrounits: __t.i64().name("local_z_microunits"),
  rotationMilliDegrees: __t.u32().name("rotation_milli_degrees"),
  sortOrder: __t.u32().name("sort_order"),
  active: __t.bool(),
});
