// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  buildingKind: __t.string().primaryKey().name("building_kind"),
  publicLabel: __t.string().name("public_label"),
  category: __t.string(),
  footprintClass: __t.string().name("footprint_class"),
  maximumLevel: __t.u32().name("maximum_level"),
  uniquePerCastle: __t.bool().name("unique_per_castle"),
  matchingDiscountResource: __t.string().name("matching_discount_resource"),
  discountBasisPointsPerLevel: __t.u32().name("discount_basis_points_per_level"),
  discountCapBasisPoints: __t.u32().name("discount_cap_basis_points"),
  runtimeAssetId: __t.string().name("runtime_asset_id"),
  previewAssetId: __t.string().name("preview_asset_id"),
  active: __t.bool(),
  policyVersion: __t.string().name("policy_version"),
});
