// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  levelKey: __t.string().primaryKey().name("level_key"),
  buildingKind: __t.string().name("building_kind"),
  targetLevel: __t.u32().name("target_level"),
  baseFoodCost: __t.u64().name("base_food_cost"),
  baseWoodCost: __t.u64().name("base_wood_cost"),
  baseStoneCost: __t.u64().name("base_stone_cost"),
  baseGoldCost: __t.u64().name("base_gold_cost"),
  levelMultiplierBasisPoints: __t.u32().name("level_multiplier_basis_points"),
  durationMicros: __t.u64().name("duration_micros"),
  policyVersion: __t.string().name("policy_version"),
});
