// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  layoutVersion: __t.u32().name("layout_version"),
  policyVersion: __t.string().name("policy_version"),
  generationVersion: __t.u32().name("generation_version"),
  canonicalLandCellCount: __t.u32().name("canonical_land_cell_count"),
  oceanCellCount: __t.u32().name("ocean_cell_count"),
  lakeCellCount: __t.u32().name("lake_cell_count"),
  lakeBodyCount: __t.u32().name("lake_body_count"),
  riverCount: __t.u32().name("river_count"),
  riverCellCount: __t.u32().name("river_cell_count"),
  seaLevelMilli: __t.i32().name("sea_level_milli"),
  seaLevelPolicyVersion: __t.string().name("sea_level_policy_version"),
  fogStartDepthCells: __t.u32().name("fog_start_depth_cells"),
  fogFullDepthCells: __t.u32().name("fog_full_depth_cells"),
  hiddenBufferCells: __t.u32().name("hidden_buffer_cells"),
  layoutDigest: __t.string().name("layout_digest"),
  sourceCommit: __t.string().name("source_commit"),
  activated: __t.bool(),
  seededAt: __t.timestamp().name("seeded_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
});
