// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bodyId: __t.string().primaryKey().name("body_id"),
  realmId: __t.string().name("realm_id"),
  regime: __t.string(),
  cellCount: __t.u32().name("cell_count"),
  sourceCellKey: __t.string().name("source_cell_key"),
  mouthCellKey: __t.string().name("mouth_cell_key"),
  surfaceLevelMilli: __t.i32().name("surface_level_milli"),
  flowDirectionXq15: __t.i32().name("flow_direction_xq_15"),
  flowDirectionZq15: __t.i32().name("flow_direction_zq_15"),
  wavePreset: __t.string().name("wave_preset"),
  ordinal: __t.u32(),
  seed: __t.u32(),
  generationVersion: __t.u32().name("generation_version"),
  layoutVersion: __t.u32().name("layout_version"),
});
