// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  channelKey: __t.string().primaryKey().name("channel_key"),
  realmId: __t.string().name("realm_id"),
  policyVersion: __t.string().name("policy_version"),
  mode: __t.string(),
  recentLimit: __t.u32().name("recent_limit"),
  historyPageLimit: __t.u32().name("history_page_limit"),
  updatedAt: __t.timestamp().name("updated_at"),
});
