// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  environmentEpoch: __t.u64().name("environment_epoch"),
  waterLayoutVersion: __t.u32().name("water_layout_version"),
  seaLevelMilli: __t.i32().name("sea_level_milli"),
  sunDirectionXMicro: __t.i32().name("sun_direction_x_micro"),
  sunDirectionYMicro: __t.i32().name("sun_direction_y_micro"),
  sunDirectionZMicro: __t.i32().name("sun_direction_z_micro"),
  updatedAt: __t.timestamp().name("updated_at"),
});
