// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  publicName: __t.string().name("public_name"),
  seedName: __t.string().name("seed_name"),
  numericSeed: __t.u32().name("numeric_seed"),
  generationVersion: __t.u32().name("generation_version"),
  authoritativeRadius: __t.u32().name("authoritative_radius"),
  renderRadius: __t.u32().name("render_radius"),
  playerCapacity: __t.u32().name("player_capacity"),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
