// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  policyVersion: __t.string().name("policy_version"),
  workersPerCastle: __t.u32().name("workers_per_castle"),
  expectedCastleCount: __t.u32().name("expected_castle_count"),
  expectedWorkerCount: __t.u32().name("expected_worker_count"),
  rosterDigest: __t.string().name("roster_digest"),
  mode: __t.string(),
  legacyDrainRequired: __t.bool().name("legacy_drain_required"),
  createdAt: __t.timestamp().name("created_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
});
