// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  revisionVersion: __t.u32().name("revision_version"),
  policyVersion: __t.string().name("policy_version"),
  baseLayoutVersion: __t.u32().name("base_layout_version"),
  baseLayoutDigest: __t.string().name("base_layout_digest"),
  oceanBodyCount: __t.u32().name("ocean_body_count"),
  riverBodyCount: __t.u32().name("river_body_count"),
  enabledBodyCount: __t.u32().name("enabled_body_count"),
  oceanCellCount: __t.u32().name("ocean_cell_count"),
  riverCellCount: __t.u32().name("river_cell_count"),
  enabledCellCount: __t.u32().name("enabled_cell_count"),
  lakeBodyCount: __t.u32().name("lake_body_count"),
  lakeCellCount: __t.u32().name("lake_cell_count"),
  riverWidthCells: __t.u32().name("river_width_cells"),
  navigationFogBoundaryDepthCells: __t.u32().name("navigation_fog_boundary_depth_cells"),
  hiddenBufferCells: __t.u32().name("hidden_buffer_cells"),
  revisionDigest: __t.string().name("revision_digest"),
  sourceCommit: __t.string().name("source_commit"),
  activated: __t.bool(),
  seededAt: __t.timestamp().name("seeded_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
});
