// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  atlasId: __t.string().primaryKey().name("atlas_id"),
  publicReleaseId: __t.string().name("public_release_id"),
  name: __t.string(),
  protocolVersion: __t.u32().name("protocol_version"),
  generatorVersion: __t.string().name("generator_version"),
  runtimePartitionVersion: __t.string().name("runtime_partition_version"),
  rendererContractVersion: __t.string().name("renderer_contract_version"),
  revision: __t.u64(),
  visibleTierMax: __t.u32().name("visible_tier_max"),
  navigationTierMax: __t.u32().name("navigation_tier_max"),
  foundingTierMax: __t.u32().name("founding_tier_max"),
  visibleRegionCount: __t.u32().name("visible_region_count"),
  visibleCellCount: __t.u32().name("visible_cell_count"),
  visibleChunkCount: __t.u32().name("visible_chunk_count"),
  castleCapacity: __t.u32().name("castle_capacity"),
  mode: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
});
