// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  realmId: __t.string().primaryKey().name("realm_id"),
  layoutVersion: __t.u32().name("layout_version"),
  policyVersion: __t.string().name("policy_version"),
  layoutDigest: __t.string().name("layout_digest"),
  assetCatalogDigest: __t.string().name("asset_catalog_digest"),
  instanceCount: __t.u32().name("instance_count"),
  seededAt: __t.timestamp().name("seeded_at"),
});
