// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cellKey: __t.string().primaryKey().name("cell_key"),
  realmId: __t.string().name("realm_id"),
  q: __t.i32(),
  r: __t.i32(),
  regime: __t.string(),
  bodyId: __t.string().name("body_id"),
  depthCells: __t.u32().name("depth_cells"),
  elevationMilli: __t.i32().name("elevation_milli"),
  surfaceLevelMilli: __t.i32().name("surface_level_milli"),
  ring: __t.u32(),
  s: __t.i32(),
  underlyingTileKey: __t.option(__t.string()).name("underlying_tile_key"),
  riverOrdinal: __t.option(__t.u32()).name("river_ordinal"),
  riverOrder: __t.option(__t.u32()).name("river_order"),
  downstreamWaterCellKey: __t.option(__t.string()).name("downstream_water_cell_key"),
  flowAccumulation: __t.u32().name("flow_accumulation"),
  depthClass: __t.u32().name("depth_class"),
  oceanDepth: __t.u32().name("ocean_depth"),
  bankSeed: __t.u32().name("bank_seed"),
  generationVersion: __t.u32().name("generation_version"),
  fogBand: __t.string().name("fog_band"),
  layoutVersion: __t.u32().name("layout_version"),
});
