// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  regionId: __t.string().primaryKey().name("region_id"),
  atlasId: __t.string().name("atlas_id"),
  ordinal: __t.u32(),
  publicName: __t.string().name("public_name"),
  tier: __t.u32(),
  cellCount: __t.u32().name("cell_count"),
  passableCellCount: __t.u32().name("passable_cell_count"),
  chunkCount: __t.u32().name("chunk_count"),
  castleCapacity: __t.u32().name("castle_capacity"),
  resourceLocationCount: __t.u32().name("resource_location_count"),
  resourceNodeCount: __t.u32().name("resource_node_count"),
  foodNodeCount: __t.u32().name("food_node_count"),
  woodNodeCount: __t.u32().name("wood_node_count"),
  stoneNodeCount: __t.u32().name("stone_node_count"),
  goldNodeCount: __t.u32().name("gold_node_count"),
  active: __t.bool(),
});
