// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  treeId: __t.string().primaryKey().name("tree_id"),
  realmId: __t.string().name("realm_id"),
  tileKey: __t.string().name("tile_key"),
  q: __t.i32(),
  r: __t.i32(),
  localXMicrounits: __t.i64().name("local_x_microunits"),
  localZMicrounits: __t.i64().name("local_z_microunits"),
  worldXMicrounits: __t.i64().name("world_x_microunits"),
  worldZMicrounits: __t.i64().name("world_z_microunits"),
  rotationMilliDegrees: __t.u32().name("rotation_milli_degrees"),
  scaleBasisPoints: __t.u32().name("scale_basis_points"),
  speciesId: __t.string().name("species_id"),
  habitat: __t.string(),
  layoutVersion: __t.u32().name("layout_version"),
});
