// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AdminAlphaStatus = __t.object("AdminAlphaStatus", {
  worldTiles: __t.u64(),
  players: __t.u64(),
  castles: __t.u64(),
  allowedFids: __t.u64(),
  enabledAllowedFids: __t.u64(),
  auditEntries: __t.u64(),
});
export type AdminAlphaStatus = __Infer<typeof AdminAlphaStatus>;

export const AdminAudit = __t.object("AdminAudit", {
  id: __t.u64(),
  action: __t.string(),
  targetFid: __t.option(__t.u64()),
  actorSubject: __t.string(),
  createdAt: __t.timestamp(),
  note: __t.string(),
});
export type AdminAudit = __Infer<typeof AdminAudit>;

export const AllowedFid = __t.object("AllowedFid", {
  fid: __t.u64(),
  enabled: __t.bool(),
  authEpoch: __t.u32(),
  invitedAt: __t.timestamp(),
  invitedBy: __t.string(),
  note: __t.string(),
});
export type AllowedFid = __Infer<typeof AllowedFid>;

export const Castle = __t.object("Castle", {
  castleId: __t.u64(),
  ownerFid: __t.u64(),
  tileKey: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  level: __t.i32(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Castle = __Infer<typeof Castle>;

export const Player = __t.object("Player", {
  fid: __t.u64(),
  identity: __t.identity(),
  username: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  status: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const WorldTile = __t.object("WorldTile", {
  key: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  biome: __t.string(),
  terrainSeed: __t.u32(),
  occupantCastleId: __t.option(__t.u64()),
});
export type WorldTile = __Infer<typeof WorldTile>;

