// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AccessRequestStatusV1 = __t.object("AccessRequestStatusV1", {
  status: __t.string(),
  requestedAtMicros: __t.option(__t.u64()),
});
export type AccessRequestStatusV1 = __Infer<typeof AccessRequestStatusV1>;

export const AccessRequestV1 = __t.object("AccessRequestV1", {
  fid: __t.u64(),
  requestCycle: __t.u64(),
  requestedAt: __t.timestamp(),
});
export type AccessRequestV1 = __Infer<typeof AccessRequestV1>;

export const AdminAccessRequestEntryV1 = __t.object("AdminAccessRequestEntryV1", {
  fid: __t.u64(),
  requestedAtMicros: __t.u64(),
  admissionState: __t.string(),
  requestState: __t.string(),
});
export type AdminAccessRequestEntryV1 = __Infer<typeof AdminAccessRequestEntryV1>;

export const AdminAccessRequestPageV1 = __t.object("AdminAccessRequestPageV1", {
  get entries() {
    return __t.array(AdminAccessRequestEntryV1);
  },
  nextRequestedAtMicros: __t.option(__t.u64()),
  nextFid: __t.option(__t.u64()),
  hasMore: __t.bool(),
  totalRequests: __t.u64(),
  pendingRequests: __t.u64(),
});
export type AdminAccessRequestPageV1 = __Infer<typeof AdminAccessRequestPageV1>;

export const AdminAccessRequestResetStatusV1 = __t.object("AdminAccessRequestResetStatusV1", {
  admissionState: __t.string(),
  authEpoch: __t.u32(),
  requestState: __t.string(),
  requestCycle: __t.option(__t.u64()),
  requestedAtMicros: __t.option(__t.u64()),
});
export type AdminAccessRequestResetStatusV1 = __Infer<typeof AdminAccessRequestResetStatusV1>;

export const AdminAlphaStatus = __t.object("AdminAlphaStatus", {
  worldTiles: __t.u64(),
  players: __t.u64(),
  castles: __t.u64(),
  allowedFids: __t.u64(),
  enabledAllowedFids: __t.u64(),
  auditEntries: __t.u64(),
});
export type AdminAlphaStatus = __Infer<typeof AdminAlphaStatus>;

export const AdminAlphaStatusV10 = __t.object("AdminAlphaStatusV10", {
  schemaProtocolVersion: __t.u32(),
  backendProtocolVersion: __t.u32(),
  waterPolicyVersion: __t.string(),
  waterLayoutVersion: __t.u32(),
  canonicalWaterLayoutDigest: __t.string(),
  waterActivated: __t.bool(),
  waterLayouts: __t.u64(),
  canonicalWaterLayouts: __t.u64(),
  waterBodies: __t.u64(),
  canonicalWaterBodies: __t.u64(),
  waterCells: __t.u64(),
  canonicalWaterCells: __t.u64(),
  realmEnvironments: __t.u64(),
  canonicalRealmEnvironments: __t.u64(),
  stoneSitePolicyVersion: __t.string(),
  stoneExpeditionPolicyVersion: __t.string(),
  canonicalStoneSiteCatalogDigest: __t.string(),
  stoneSites: __t.u64(),
  canonicalStoneSites: __t.u64(),
  stoneOccupations: __t.u64(),
  stoneExpeditions: __t.u64(),
  stoneIdempotencyReceipts: __t.u64(),
  stoneSchedules: __t.u64(),
});
export type AdminAlphaStatusV10 = __Infer<typeof AdminAlphaStatusV10>;

export const AdminAlphaStatusV2 = __t.object("AdminAlphaStatusV2", {
  worldTiles: __t.u64(),
  legacyPlayers: __t.u64(),
  playersV2: __t.u64(),
  playerOwnershipsV2: __t.u64(),
  consistentPlayerPairsV2: __t.u64(),
  orphanedPlayerRowsV2: __t.u64(),
  orphanedOwnershipRowsV2: __t.u64(),
  castles: __t.u64(),
  allowedFids: __t.u64(),
  enabledAllowedFids: __t.u64(),
  auditEntries: __t.u64(),
  protocolVersion: __t.u32(),
  worldSeed: __t.u32(),
  worldSeedName: __t.string(),
});
export type AdminAlphaStatusV2 = __Infer<typeof AdminAlphaStatusV2>;

export const AdminAlphaStatusV3 = __t.object("AdminAlphaStatusV3", {
  worldTiles: __t.u64(),
  occupiedWorldTiles: __t.u64(),
  worldTileMeta: __t.u64(),
  realms: __t.u64(),
  castleSlots: __t.u64(),
  castleSlotClaims: __t.u64(),
  legacyPlayers: __t.u64(),
  playersV2: __t.u64(),
  playerOwnershipsV2: __t.u64(),
  castles: __t.u64(),
  realmProfiles: __t.u64(),
  markAccounts: __t.u64(),
  snapBurnCredits: __t.u64(),
  walletAttributions: __t.u64(),
  walletAttributionSnapshots: __t.u64(),
  scanCursors: __t.u64(),
  scanBatches: __t.u64(),
  alphaTermsAcceptances: __t.u64(),
  allowedFids: __t.u64(),
  enabledAllowedFids: __t.u64(),
  auditEntries: __t.u64(),
  orphanedPlayerRowsV2: __t.u64(),
  orphanedOwnershipRowsV2: __t.u64(),
  orphanedCastleClaims: __t.u64(),
  orphanedCastles: __t.u64(),
  orphanedRealmProfiles: __t.u64(),
  orphanedMarkAccounts: __t.u64(),
  orphanedBurnCredits: __t.u64(),
  orphanedTermsAcceptances: __t.u64(),
  founderStateGaps: __t.u64(),
  markAccountInvariantViolations: __t.u64(),
  publicMarkProjectionViolations: __t.u64(),
  duplicateBurnReferences: __t.u64(),
  burnAccountReconciliationViolations: __t.u64(),
  ambiguousActiveWalletAddresses: __t.u64(),
  staticWorldDriftViolations: __t.u64(),
  termsAcceptanceInvariantViolations: __t.u64(),
  protocolVersion: __t.u32(),
  worldSeed: __t.u32(),
  worldSeedName: __t.string(),
});
export type AdminAlphaStatusV3 = __Infer<typeof AdminAlphaStatusV3>;

export const AdminAlphaStatusV4 = __t.object("AdminAlphaStatusV4", {
  allowedFids: __t.u64(),
  castles: __t.u64(),
  markAccounts: __t.u64(),
  resourceAccounts: __t.u64(),
  missingResourceAccounts: __t.u64(),
  orphanedResourceAccounts: __t.u64(),
  resourceInvariantViolations: __t.u64(),
  protocolVersion: __t.u32(),
  resourcePolicyVersion: __t.string(),
});
export type AdminAlphaStatusV4 = __Infer<typeof AdminAlphaStatusV4>;

export const AdminAlphaStatusV8 = __t.object("AdminAlphaStatusV8", {
  schemaProtocolVersion: __t.u32(),
  backendProtocolVersion: __t.u32(),
  goldSitePolicyVersion: __t.string(),
  goldExpeditionPolicyVersion: __t.string(),
  canonicalGoldSiteCatalogDigest: __t.string(),
  goldSites: __t.u64(),
  canonicalGoldSites: __t.u64(),
  goldOccupations: __t.u64(),
  goldExpeditions: __t.u64(),
  goldIdempotencyReceipts: __t.u64(),
  goldSchedules: __t.u64(),
  forestLayoutVersion: __t.u32(),
  forestPolicyVersion: __t.string(),
  canonicalForestLayoutDigest: __t.string(),
  canonicalForestAssetCatalogDigest: __t.string(),
  forestLayouts: __t.u64(),
  canonicalForestLayouts: __t.u64(),
  forestInstances: __t.u64(),
  canonicalForestInstances: __t.u64(),
  foodSitePolicyVersion: __t.string(),
  foodExpeditionPolicyVersion: __t.string(),
  canonicalFoodSiteCatalogDigest: __t.string(),
  foodSites: __t.u64(),
  canonicalFoodSites: __t.u64(),
  foodOccupations: __t.u64(),
  foodExpeditions: __t.u64(),
  foodIdempotencyReceipts: __t.u64(),
  foodSchedules: __t.u64(),
  woodSitePolicyVersion: __t.string(),
  woodExpeditionPolicyVersion: __t.string(),
  canonicalWoodSiteCatalogDigest: __t.string(),
  woodSites: __t.u64(),
  canonicalWoodSites: __t.u64(),
  woodOccupations: __t.u64(),
  woodExpeditions: __t.u64(),
  woodIdempotencyReceipts: __t.u64(),
  woodSchedules: __t.u64(),
});
export type AdminAlphaStatusV8 = __Infer<typeof AdminAlphaStatusV8>;

export const AdminAudit = __t.object("AdminAudit", {
  id: __t.u64(),
  action: __t.string(),
  targetFid: __t.option(__t.u64()),
  actorSubject: __t.string(),
  createdAt: __t.timestamp(),
  note: __t.string(),
});
export type AdminAudit = __Infer<typeof AdminAudit>;

export const AdminDailyMarksStatusV1 = __t.object("AdminDailyMarksStatusV1", {
  policyVersion: __t.string(),
  utcDay: __t.u64(),
  allowedFids: __t.u64(),
  enabledAllowedFids: __t.u64(),
  markAccounts: __t.u64(),
  dailyAccounts: __t.u64(),
  legacyZeroAccounts: __t.u64(),
  invalidAccounts: __t.u64(),
  realmProfiles: __t.u64(),
  profileProjectionViolations: __t.u64(),
  missingFounderState: __t.u64(),
  grants: __t.u64(),
  currentDayGrants: __t.u64(),
  grantInvariantViolations: __t.u64(),
  grantAccountReconciliationViolations: __t.u64(),
  scheduleRows: __t.u64(),
  scheduleConfigValid: __t.bool(),
  legacyCompatibilityRows: __t.u64(),
  readyForBackfill: __t.bool(),
  readyForActivation: __t.bool(),
  active: __t.bool(),
});
export type AdminDailyMarksStatusV1 = __Infer<typeof AdminDailyMarksStatusV1>;

export const AdminInnerKeepBuilderPlanV1 = __t.object("AdminInnerKeepBuilderPlanV1", {
  expectedCastles: __t.u32(),
  existingBuilders: __t.u32(),
  missingBuilders: __t.u32(),
  ready: __t.bool(),
});
export type AdminInnerKeepBuilderPlanV1 = __Infer<typeof AdminInnerKeepBuilderPlanV1>;

export const AdminInnerKeepCatalogPlanV1 = __t.object("AdminInnerKeepCatalogPlanV1", {
  missingLayout: __t.u32(),
  missingSlots: __t.u32(),
  missingBuildings: __t.u32(),
  missingLevels: __t.u32(),
  ready: __t.bool(),
});
export type AdminInnerKeepCatalogPlanV1 = __Infer<typeof AdminInnerKeepCatalogPlanV1>;

export const AdminInnerKeepStatusV1 = __t.object("AdminInnerKeepStatusV1", {
  layoutRows: __t.u64(),
  slotRows: __t.u64(),
  buildingCatalogRows: __t.u64(),
  levelPolicyRows: __t.u64(),
  castleRows: __t.u64(),
  builderRows: __t.u64(),
  buildingRows: __t.u64(),
  activeProjects: __t.u64(),
  receiptRows: __t.u64(),
  scheduleRows: __t.u64(),
  missingBuilders: __t.u64(),
  orphanBuilders: __t.u64(),
  invalidBuilders: __t.u64(),
  invalidBuildings: __t.u64(),
  invalidSchedules: __t.u64(),
  builderProjectMismatches: __t.u64(),
  staticCatalogExact: __t.bool(),
  workerSystemReady: __t.bool(),
  readyForCatalogSeed: __t.bool(),
  readyForBuilderBackfill: __t.bool(),
  readyForActivation: __t.bool(),
  active: __t.bool(),
  policyVersion: __t.string(),
  policyDigest: __t.string(),
  layoutPolicyVersion: __t.string(),
  layoutDigest: __t.string(),
  assetCatalogDigest: __t.string(),
});
export type AdminInnerKeepStatusV1 = __Infer<typeof AdminInnerKeepStatusV1>;

export const AdminRealmChatReportContextV1 = __t.object("AdminRealmChatReportContextV1", {
  get report() {
    return AdminRealmChatReportEntryV1;
  },
  get messages() {
    return __t.array(RealmChatMessageProjectionV1);
  },
});
export type AdminRealmChatReportContextV1 = __Infer<typeof AdminRealmChatReportContextV1>;

export const AdminRealmChatReportEntryV1 = __t.object("AdminRealmChatReportEntryV1", {
  reportOrdinal: __t.u64(),
  reportId: __t.string(),
  reporterFid: __t.u64(),
  messageId: __t.string(),
  reportedSenderFid: __t.u64(),
  messageSequence: __t.u64(),
  category: __t.string(),
  details: __t.string(),
  contextFirstSequence: __t.u64(),
  contextLastSequence: __t.u64(),
  createdAtMicros: __t.u64(),
  status: __t.string(),
  reviewedAtMicros: __t.option(__t.u64()),
  resolutionCode: __t.option(__t.string()),
});
export type AdminRealmChatReportEntryV1 = __Infer<typeof AdminRealmChatReportEntryV1>;

export const AdminRealmChatReportPageV1 = __t.object("AdminRealmChatReportPageV1", {
  get reports() {
    return __t.array(AdminRealmChatReportEntryV1);
  },
  nextBeforeOrdinal: __t.option(__t.u64()),
  hasMore: __t.bool(),
  totalReports: __t.u64(),
});
export type AdminRealmChatReportPageV1 = __Infer<typeof AdminRealmChatReportPageV1>;

export const AdminRealmChatStatusV1 = __t.object("AdminRealmChatStatusV1", {
  channelKey: __t.string(),
  policyVersion: __t.string(),
  mode: __t.string(),
  nextSequence: __t.u64(),
  archivedMessages: __t.u64(),
  recentMessages: __t.u64(),
  reports: __t.u64(),
  rateEvents: __t.u64(),
  sendReceipts: __t.u64(),
  graphValid: __t.bool(),
  activationCompiled: __t.bool(),
});
export type AdminRealmChatStatusV1 = __Infer<typeof AdminRealmChatStatusV1>;

export const AdminWaterLayoutStatusV1 = __t.object("AdminWaterLayoutStatusV1", {
  ready: __t.bool(),
  activated: __t.bool(),
  layoutVersion: __t.u32(),
  layoutDigest: __t.string(),
  canonicalLandCellCount: __t.u32(),
  oceanCellCount: __t.u32(),
  lakeCellCount: __t.u32(),
  lakeBodyCount: __t.u32(),
  riverCount: __t.u32(),
  riverCellCount: __t.u32(),
  waterBodies: __t.u64(),
  canonicalWaterBodies: __t.u64(),
  waterCells: __t.u64(),
  canonicalWaterCells: __t.u64(),
  environmentRows: __t.u64(),
  sourceCommit: __t.string(),
});
export type AdminWaterLayoutStatusV1 = __Infer<typeof AdminWaterLayoutStatusV1>;

export const AdminWaterRevisionStatusV1 = __t.object("AdminWaterRevisionStatusV1", {
  ready: __t.bool(),
  activated: __t.bool(),
  revisionVersion: __t.u32(),
  policyVersion: __t.string(),
  baseLayoutVersion: __t.u32(),
  baseLayoutDigest: __t.string(),
  oceanBodyCount: __t.u32(),
  riverBodyCount: __t.u32(),
  enabledBodyCount: __t.u32(),
  oceanCellCount: __t.u32(),
  riverCellCount: __t.u32(),
  enabledCellCount: __t.u32(),
  lakeBodyCount: __t.u32(),
  lakeCellCount: __t.u32(),
  riverWidthCells: __t.u32(),
  navigationFogBoundaryDepthCells: __t.u32(),
  hiddenBufferCells: __t.u32(),
  revisionRows: __t.u64(),
  revisionDigest: __t.string(),
  sourceCommit: __t.string(),
});
export type AdminWaterRevisionStatusV1 = __Infer<typeof AdminWaterRevisionStatusV1>;

export const AdminWorkerRolloutStatusV2 = __t.object("AdminWorkerRolloutStatusV2", {
  phase: __t.string(),
  systemRows: __t.u64(),
  systemConfigValid: __t.bool(),
  expectedCastleCount: __t.u32(),
  expectedWorkerCount: __t.u32(),
  actualCastleCount: __t.u64(),
  actualWorkerCount: __t.u64(),
  rosterDigest: __t.string(),
  expectedRosterDigest: __t.string(),
  malformedWorkerGraphRows: __t.u64(),
  resourceAccounts: __t.u64(),
  missingResourceAccounts: __t.u64(),
  orphanedResourceAccounts: __t.u64(),
  resourceInvariantViolations: __t.u64(),
  resourceRosterDigest: __t.string(),
  canonicalResourceCatalog: __t.bool(),
  resourceCatalogDigest: __t.string(),
  legacyExpeditions: __t.u64(),
  legacyOccupations: __t.u64(),
  legacySchedules: __t.u64(),
  legacyGoldExpeditions: __t.u64(),
  legacyFoodExpeditions: __t.u64(),
  legacyWoodExpeditions: __t.u64(),
  legacyStoneExpeditions: __t.u64(),
  legacyGoldOccupations: __t.u64(),
  legacyFoodOccupations: __t.u64(),
  legacyWoodOccupations: __t.u64(),
  legacyStoneOccupations: __t.u64(),
  legacyGoldSchedules: __t.u64(),
  legacyFoodSchedules: __t.u64(),
  legacyWoodSchedules: __t.u64(),
  legacyStoneSchedules: __t.u64(),
  genericAssignments: __t.u64(),
  genericOccupations: __t.u64(),
  genericSchedules: __t.u64(),
  genericCommandReceipts: __t.u64(),
});
export type AdminWorkerRolloutStatusV2 = __Infer<typeof AdminWorkerRolloutStatusV2>;

export const AdminWorkerRosterPlanV1 = __t.object("AdminWorkerRosterPlanV1", {
  ready: __t.bool(),
  activationBlockedByLegacyRows: __t.bool(),
  mode: __t.string(),
  systemConfigValid: __t.bool(),
  legacyDrainRequired: __t.bool(),
  expectedCastleCount: __t.u64(),
  expectedWorkerCount: __t.u64(),
  actualWorkerCount: __t.u64(),
  expectedCountsMatch: __t.bool(),
  rosterDigestMatches: __t.bool(),
  castlesMissingWorkers: __t.u64(),
  castlesWithExtraWorkers: __t.u64(),
  orphanWorkers: __t.u64(),
  orphanAssignments: __t.u64(),
  assignmentsMissingOccupation: __t.u64(),
  assignmentsWithoutSingleSchedule: __t.u64(),
  orphanOccupations: __t.u64(),
  orphanSchedules: __t.u64(),
  invalidSchedules: __t.u64(),
  assignmentPublicMismatches: __t.u64(),
  occupationSiteMismatches: __t.u64(),
  invalidWorkerStates: __t.u64(),
  invalidAssignments: __t.u64(),
  invalidIdempotencyReceipts: __t.u64(),
  idempotencyOverflowFids: __t.u64(),
  legacyExpeditions: __t.u64(),
  legacyOccupations: __t.u64(),
  legacySchedules: __t.u64(),
  rosterDigest: __t.string(),
  rosterDigestExpected: __t.string(),
});
export type AdminWorkerRosterPlanV1 = __Infer<typeof AdminWorkerRosterPlanV1>;

export const AdminWorkerSystemStatusV1 = __t.object("AdminWorkerSystemStatusV1", {
  systemRows: __t.u64(),
  mode: __t.string(),
  systemConfigValid: __t.bool(),
  legacyDrainRequired: __t.bool(),
  expectedCastleCount: __t.u64(),
  expectedWorkerCount: __t.u64(),
  actualWorkerCount: __t.u64(),
  expectedCountsMatch: __t.bool(),
  rosterDigestMatches: __t.bool(),
  castlesMissingWorkers: __t.u64(),
  castlesWithExtraWorkers: __t.u64(),
  duplicateOrdinals: __t.u64(),
  malformedWorkerIds: __t.u64(),
  invalidWorkerStates: __t.u64(),
  idleWorkers: __t.u64(),
  outboundWorkers: __t.u64(),
  gatheringWorkers: __t.u64(),
  returningWorkers: __t.u64(),
  assignments: __t.u64(),
  occupations: __t.u64(),
  schedules: __t.u64(),
  orphanWorkers: __t.u64(),
  orphanAssignments: __t.u64(),
  assignmentsMissingOccupation: __t.u64(),
  assignmentsWithoutSingleSchedule: __t.u64(),
  orphanOccupations: __t.u64(),
  orphanSchedules: __t.u64(),
  invalidSchedules: __t.u64(),
  assignmentPublicMismatches: __t.u64(),
  occupationSiteMismatches: __t.u64(),
  invalidAssignments: __t.u64(),
  idempotencyReceipts: __t.u64(),
  invalidIdempotencyReceipts: __t.u64(),
  idempotencyOverflowFids: __t.u64(),
  legacyExpeditions: __t.u64(),
  legacyOccupations: __t.u64(),
  legacySchedules: __t.u64(),
  rosterDigest: __t.string(),
  rosterDigestExpected: __t.string(),
});
export type AdminWorkerSystemStatusV1 = __Infer<typeof AdminWorkerSystemStatusV1>;

export const AllowedFid = __t.object("AllowedFid", {
  fid: __t.u64(),
  enabled: __t.bool(),
  authEpoch: __t.u32(),
  invitedAt: __t.timestamp(),
  invitedBy: __t.string(),
  note: __t.string(),
});
export type AllowedFid = __Infer<typeof AllowedFid>;

export const AlphaBackendInfo = __t.object("AlphaBackendInfo", {
  protocolVersion: __t.u32(),
  worldSeed: __t.u32(),
  worldSeedName: __t.string(),
});
export type AlphaBackendInfo = __Infer<typeof AlphaBackendInfo>;

export const AlphaTermsAcceptanceV1 = __t.object("AlphaTermsAcceptanceV1", {
  acceptanceKey: __t.string(),
  fid: __t.u64(),
  termsVersion: __t.string(),
  acceptedAt: __t.timestamp(),
});
export type AlphaTermsAcceptanceV1 = __Infer<typeof AlphaTermsAcceptanceV1>;

export const AuthResolverFidAdmissionV2 = __t.object("AuthResolverFidAdmissionV2", {
  state: __t.string(),
  authEpoch: __t.u32(),
});
export type AuthResolverFidAdmissionV2 = __Infer<typeof AuthResolverFidAdmissionV2>;

export const Castle = __t.object("Castle", {
  castleId: __t.u64(),
  ownerFid: __t.u64(),
  tileKey: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  level: __t.i32(),
  name: __t.string(),
  createdAt: __t.timestamp(),
});
export type Castle = __Infer<typeof Castle>;

export const CastleInnerBuildReceiptV1 = __t.object("CastleInnerBuildReceiptV1", {
  receiptKey: __t.string(),
  fid: __t.u64(),
  requestKey: __t.string(),
  castleId: __t.u64(),
  buildingKey: __t.string(),
  buildingKind: __t.string(),
  localXMicrounits: __t.i64(),
  localZMicrounits: __t.i64(),
  rotationMilliDegrees: __t.u32(),
  targetLevel: __t.u32(),
  deductedFood: __t.u64(),
  deductedWood: __t.u64(),
  deductedStone: __t.u64(),
  deductedGold: __t.u64(),
  startedAt: __t.timestamp(),
  policyVersion: __t.string(),
});
export type CastleInnerBuildReceiptV1 = __Infer<typeof CastleInnerBuildReceiptV1>;

export const CastleInnerBuilderV1 = __t.object("CastleInnerBuilderV1", {
  castleId: __t.u64(),
  fid: __t.u64(),
  activeBuildingKey: __t.option(__t.string()),
  busyUntilMicros: __t.option(__t.u64()),
  revision: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type CastleInnerBuilderV1 = __Infer<typeof CastleInnerBuilderV1>;

export const CastleInnerConstructionScheduleV1 = __t.object("CastleInnerConstructionScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  buildingKey: __t.string(),
  expectedRevision: __t.u64(),
  expectedTargetLevel: __t.u32(),
});
export type CastleInnerConstructionScheduleV1 = __Infer<typeof CastleInnerConstructionScheduleV1>;

export const CastleInnerKeepBuildingV1 = __t.object("CastleInnerKeepBuildingV1", {
  buildingKey: __t.string(),
  castleId: __t.u64(),
  buildingKind: __t.string(),
  localXMicrounits: __t.i64(),
  localZMicrounits: __t.i64(),
  rotationMilliDegrees: __t.u32(),
  completedLevel: __t.u32(),
  targetLevel: __t.u32(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  completesAtMicros: __t.u64(),
  revision: __t.u64(),
  policyVersion: __t.string(),
});
export type CastleInnerKeepBuildingV1 = __Infer<typeof CastleInnerKeepBuildingV1>;

export const CastleSlotClaimV1 = __t.object("CastleSlotClaimV1", {
  slotId: __t.u32(),
  ownerFid: __t.u64(),
  castleId: __t.u64(),
  claimedAt: __t.timestamp(),
  generationVersion: __t.u32(),
});
export type CastleSlotClaimV1 = __Infer<typeof CastleSlotClaimV1>;

export const CastleSlotV1 = __t.object("CastleSlotV1", {
  slotId: __t.u32(),
  realmId: __t.string(),
  tileKey: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  generationVersion: __t.u32(),
});
export type CastleSlotV1 = __Infer<typeof CastleSlotV1>;

export const CastleWorkerV1 = __t.object("CastleWorkerV1", {
  workerId: __t.string(),
  originCastleId: __t.u64(),
  ordinal: __t.u32(),
  status: __t.string(),
  resourceKind: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  startedAtMicros: __t.option(__t.u64()),
  arrivesAtMicros: __t.option(__t.u64()),
  gatheringEndsAtMicros: __t.option(__t.u64()),
  returnStartedAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.option(__t.u64()),
  routeSteps: __t.option(__t.u32()),
  returnStartProgressBasisPoints: __t.option(__t.u32()),
  timelineRevision: __t.u32(),
  revision: __t.u64(),
});
export type CastleWorkerV1 = __Infer<typeof CastleWorkerV1>;

export const DailyMarkGrantV1 = __t.object("DailyMarkGrantV1", {
  grantKey: __t.string(),
  fid: __t.u64(),
  utcDay: __t.u64(),
  amountMicros: __t.u128(),
  policyVersion: __t.string(),
  grantedAt: __t.timestamp(),
});
export type DailyMarkGrantV1 = __Infer<typeof DailyMarkGrantV1>;

export const DailyMarkScheduleV1 = __t.object("DailyMarkScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  policyVersion: __t.string(),
});
export type DailyMarkScheduleV1 = __Infer<typeof DailyMarkScheduleV1>;

export const FidWalletAttributionV1 = __t.object("FidWalletAttributionV1", {
  snapshotAttributionKey: __t.string(),
  attributionKey: __t.string(),
  snapshotGeneration: __t.u64(),
  fid: __t.u64(),
  address: __t.string(),
  addressType: __t.string(),
  source: __t.string(),
  snapshotAt: __t.timestamp(),
  attributionPolicyVersion: __t.string(),
  active: __t.bool(),
});
export type FidWalletAttributionV1 = __Infer<typeof FidWalletAttributionV1>;

export const FoodExpeditionIdempotencyV1 = __t.object("FoodExpeditionIdempotencyV1", {
  requestKey: __t.string(),
  fid: __t.u64(),
  siteId: __t.string(),
  expeditionId: __t.string(),
  createdAt: __t.timestamp(),
});
export type FoodExpeditionIdempotencyV1 = __Infer<typeof FoodExpeditionIdempotencyV1>;

export const FoodExpeditionScheduleV1 = __t.object("FoodExpeditionScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  stage: __t.string(),
});
export type FoodExpeditionScheduleV1 = __Infer<typeof FoodExpeditionScheduleV1>;

export const FoodExpeditionV1 = __t.object("FoodExpeditionV1", {
  expeditionId: __t.string(),
  fid: __t.u64(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  accruedFood: __t.u64(),
  creditedFood: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type FoodExpeditionV1 = __Infer<typeof FoodExpeditionV1>;

export const FoodNodeOccupationV1 = __t.object("FoodNodeOccupationV1", {
  siteId: __t.string(),
  originCastleId: __t.u64(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
});
export type FoodNodeOccupationV1 = __Infer<typeof FoodNodeOccupationV1>;

export const FoodSiteV1 = __t.object("FoodSiteV1", {
  siteId: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  tier: __t.u32(),
  active: __t.bool(),
});
export type FoodSiteV1 = __Infer<typeof FoodSiteV1>;

export const GoldExpeditionIdempotencyV1 = __t.object("GoldExpeditionIdempotencyV1", {
  requestKey: __t.string(),
  fid: __t.u64(),
  siteId: __t.string(),
  expeditionId: __t.string(),
  createdAt: __t.timestamp(),
});
export type GoldExpeditionIdempotencyV1 = __Infer<typeof GoldExpeditionIdempotencyV1>;

export const GoldExpeditionScheduleV1 = __t.object("GoldExpeditionScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  stage: __t.string(),
});
export type GoldExpeditionScheduleV1 = __Infer<typeof GoldExpeditionScheduleV1>;

export const GoldExpeditionV1 = __t.object("GoldExpeditionV1", {
  expeditionId: __t.string(),
  fid: __t.u64(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  accruedGold: __t.u64(),
  creditedGold: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type GoldExpeditionV1 = __Infer<typeof GoldExpeditionV1>;

export const GoldNodeOccupationV1 = __t.object("GoldNodeOccupationV1", {
  siteId: __t.string(),
  originCastleId: __t.u64(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
});
export type GoldNodeOccupationV1 = __Infer<typeof GoldNodeOccupationV1>;

export const GoldSiteV1 = __t.object("GoldSiteV1", {
  siteId: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  tier: __t.u32(),
  active: __t.bool(),
});
export type GoldSiteV1 = __Infer<typeof GoldSiteV1>;

export const InnerKeepBuildLevelV1 = __t.object("InnerKeepBuildLevelV1", {
  levelKey: __t.string(),
  buildingKind: __t.string(),
  targetLevel: __t.u32(),
  baseFoodCost: __t.u64(),
  baseWoodCost: __t.u64(),
  baseStoneCost: __t.u64(),
  baseGoldCost: __t.u64(),
  levelMultiplierBasisPoints: __t.u32(),
  durationMicros: __t.u64(),
  policyVersion: __t.string(),
});
export type InnerKeepBuildLevelV1 = __Infer<typeof InnerKeepBuildLevelV1>;

export const InnerKeepBuildingCatalogV1 = __t.object("InnerKeepBuildingCatalogV1", {
  buildingKind: __t.string(),
  publicLabel: __t.string(),
  category: __t.string(),
  footprintClass: __t.string(),
  maximumLevel: __t.u32(),
  uniquePerCastle: __t.bool(),
  matchingDiscountResource: __t.string(),
  discountBasisPointsPerLevel: __t.u32(),
  discountCapBasisPoints: __t.u32(),
  runtimeAssetId: __t.string(),
  previewAssetId: __t.string(),
  active: __t.bool(),
  policyVersion: __t.string(),
});
export type InnerKeepBuildingCatalogV1 = __Infer<typeof InnerKeepBuildingCatalogV1>;

export const InnerKeepLayoutV1 = __t.object("InnerKeepLayoutV1", {
  layoutId: __t.string(),
  layoutVersion: __t.u32(),
  policyVersion: __t.string(),
  slotCount: __t.u32(),
  mediumSlotCount: __t.u32(),
  largeSlotCount: __t.u32(),
  assetCatalogDigest: __t.string(),
  layoutDigest: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  activatedAt: __t.option(__t.timestamp()),
});
export type InnerKeepLayoutV1 = __Infer<typeof InnerKeepLayoutV1>;

export const InnerKeepSlotV1 = __t.object("InnerKeepSlotV1", {
  slotId: __t.string(),
  layoutId: __t.string(),
  footprintClass: __t.string(),
  localXMicrounits: __t.i64(),
  localZMicrounits: __t.i64(),
  rotationMilliDegrees: __t.u32(),
  sortOrder: __t.u32(),
  active: __t.bool(),
});
export type InnerKeepSlotV1 = __Infer<typeof InnerKeepSlotV1>;

export const MarkAccountV1 = __t.object("MarkAccountV1", {
  fid: __t.u64(),
  totalSnapBurnedMicros: __t.u128(),
  earnedMicros: __t.u128(),
  spentMicros: __t.u128(),
  balanceMicros: __t.u128(),
  policyVersion: __t.string(),
  updatedAt: __t.timestamp(),
});
export type MarkAccountV1 = __Infer<typeof MarkAccountV1>;

export const MyEntryAgreementStatusV1 = __t.object("MyEntryAgreementStatusV1", {
  requiredVersion: __t.string(),
  acceptedCurrent: __t.bool(),
});
export type MyEntryAgreementStatusV1 = __Infer<typeof MyEntryAgreementStatusV1>;

export const MyFoodExpeditionStateV1 = __t.object("MyFoodExpeditionStateV1", {
  active: __t.bool(),
  expeditionId: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  originCastleId: __t.option(__t.u64()),
  phase: __t.option(__t.string()),
  startedAtMicros: __t.option(__t.u64()),
  arrivesAtMicros: __t.option(__t.u64()),
  gatheringEndsAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.option(__t.u64()),
  accruedFood: __t.u64(),
  pendingFood: __t.u64(),
  creditedFood: __t.u64(),
  rateFoodPerMinute: __t.u64(),
  gatheringDurationMicros: __t.u64(),
  expeditionPolicyVersion: __t.option(__t.string()),
});
export type MyFoodExpeditionStateV1 = __Infer<typeof MyFoodExpeditionStateV1>;

export const MyGoldExpeditionStateV1 = __t.object("MyGoldExpeditionStateV1", {
  active: __t.bool(),
  expeditionId: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  originCastleId: __t.option(__t.u64()),
  phase: __t.option(__t.string()),
  startedAtMicros: __t.option(__t.u64()),
  arrivesAtMicros: __t.option(__t.u64()),
  gatheringEndsAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.option(__t.u64()),
  accruedGold: __t.u64(),
  pendingGold: __t.u64(),
  creditedGold: __t.u64(),
  rateGoldPerMinute: __t.u64(),
  gatheringDurationMicros: __t.u64(),
  expeditionPolicyVersion: __t.option(__t.string()),
});
export type MyGoldExpeditionStateV1 = __Infer<typeof MyGoldExpeditionStateV1>;

export const MyInnerKeepRequestStatusV1 = __t.object("MyInnerKeepRequestStatusV1", {
  found: __t.bool(),
  castleId: __t.option(__t.u64()),
  buildingKey: __t.option(__t.string()),
  buildingKind: __t.option(__t.string()),
  localXMicrounits: __t.option(__t.i64()),
  localZMicrounits: __t.option(__t.i64()),
  rotationMilliDegrees: __t.option(__t.u32()),
  targetLevel: __t.option(__t.u32()),
  deductedFood: __t.option(__t.u64()),
  deductedWood: __t.option(__t.u64()),
  deductedStone: __t.option(__t.u64()),
  deductedGold: __t.option(__t.u64()),
  startedAtMicros: __t.option(__t.u64()),
  policyVersion: __t.option(__t.string()),
});
export type MyInnerKeepRequestStatusV1 = __Infer<typeof MyInnerKeepRequestStatusV1>;

export const MyInnerKeepStateV1 = __t.object("MyInnerKeepStateV1", {
  castleId: __t.u64(),
  componentActive: __t.bool(),
  componentReady: __t.bool(),
  builderPresent: __t.bool(),
  builderBusy: __t.bool(),
  activeBuildingKey: __t.option(__t.string()),
  busyUntilMicros: __t.option(__t.u64()),
  builderRevision: __t.u64(),
  storedFood: __t.u64(),
  storedWood: __t.u64(),
  storedStone: __t.u64(),
  storedGold: __t.u64(),
  projectedFood: __t.u64(),
  projectedWood: __t.u64(),
  projectedStone: __t.u64(),
  projectedGold: __t.u64(),
  resourceRevision: __t.u64(),
  observedAtMicros: __t.u64(),
  policyVersion: __t.string(),
  layoutDigest: __t.string(),
  assetCatalogDigest: __t.string(),
});
export type MyInnerKeepStateV1 = __Infer<typeof MyInnerKeepStateV1>;

export const MyResourceStateV1 = __t.object("MyResourceStateV1", {
  fid: __t.u64(),
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  pendingFood: __t.u64(),
  pendingWood: __t.u64(),
  pendingStone: __t.u64(),
  pendingGold: __t.u64(),
  marksBalanceMicros: __t.u128(),
  observedAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  nextCollectAtMicros: __t.u64(),
  revision: __t.u64(),
  resourcePolicyVersion: __t.string(),
  marksPolicyVersion: __t.string(),
  terrainKind: __t.string(),
});
export type MyResourceStateV1 = __Infer<typeof MyResourceStateV1>;

export const MyResourceStateV2 = __t.object("MyResourceStateV2", {
  fid: __t.u64(),
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  workerPendingFood: __t.u64(),
  workerPendingWood: __t.u64(),
  workerPendingStone: __t.u64(),
  workerPendingGold: __t.u64(),
  observedAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  revision: __t.u64(),
  resourcePolicyVersion: __t.string(),
  workerPolicyVersion: __t.string(),
  workerSystemMode: __t.string(),
});
export type MyResourceStateV2 = __Infer<typeof MyResourceStateV2>;

export const MyStoneExpeditionStateV1 = __t.object("MyStoneExpeditionStateV1", {
  active: __t.bool(),
  expeditionId: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  originCastleId: __t.option(__t.u64()),
  phase: __t.option(__t.string()),
  startedAtMicros: __t.option(__t.u64()),
  arrivesAtMicros: __t.option(__t.u64()),
  gatheringEndsAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.option(__t.u64()),
  accruedStone: __t.u64(),
  pendingStone: __t.u64(),
  creditedStone: __t.u64(),
  rateStonePerMinute: __t.u64(),
  gatheringDurationMicros: __t.u64(),
  expeditionPolicyVersion: __t.option(__t.string()),
});
export type MyStoneExpeditionStateV1 = __Infer<typeof MyStoneExpeditionStateV1>;

export const MyWoodExpeditionStateV1 = __t.object("MyWoodExpeditionStateV1", {
  active: __t.bool(),
  expeditionId: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  originCastleId: __t.option(__t.u64()),
  phase: __t.option(__t.string()),
  startedAtMicros: __t.option(__t.u64()),
  arrivesAtMicros: __t.option(__t.u64()),
  gatheringEndsAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.option(__t.u64()),
  accruedWood: __t.u64(),
  pendingWood: __t.u64(),
  creditedWood: __t.u64(),
  rateWoodPerMinute: __t.u64(),
  gatheringDurationMicros: __t.u64(),
  expeditionPolicyVersion: __t.option(__t.string()),
});
export type MyWoodExpeditionStateV1 = __Infer<typeof MyWoodExpeditionStateV1>;

export const MyWorkerControlStateV1 = __t.object("MyWorkerControlStateV1", {
  fid: __t.u64(),
  castleId: __t.u64(),
  observedAtMicros: __t.u64(),
  get workers() {
    return __t.array(WorkerPrivateV1);
  },
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  workerPendingFood: __t.u64(),
  workerPendingWood: __t.u64(),
  workerPendingStone: __t.u64(),
  workerPendingGold: __t.u64(),
  settledThroughMicros: __t.u64(),
  revision: __t.u64(),
  resourcePolicyVersion: __t.string(),
  workerPolicyVersion: __t.string(),
  workerSystemMode: __t.string(),
});
export type MyWorkerControlStateV1 = __Infer<typeof MyWorkerControlStateV1>;

export const MyWorkerRosterV1 = __t.object("MyWorkerRosterV1", {
  fid: __t.u64(),
  castleId: __t.u64(),
  observedAtMicros: __t.u64(),
  get workers() {
    return __t.array(WorkerPrivateV1);
  },
});
export type MyWorkerRosterV1 = __Infer<typeof MyWorkerRosterV1>;

export const Player = __t.object("Player", {
  fid: __t.u64(),
  identity: __t.identity(),
  username: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  status: __t.string(),
});
export type Player = __Infer<typeof Player>;

export const PlayerOwnershipV2 = __t.object("PlayerOwnershipV2", {
  fid: __t.u64(),
  identity: __t.identity(),
});
export type PlayerOwnershipV2 = __Infer<typeof PlayerOwnershipV2>;

export const PlayerV2 = __t.object("PlayerV2", {
  fid: __t.u64(),
  username: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  joinedAt: __t.timestamp(),
  status: __t.string(),
});
export type PlayerV2 = __Infer<typeof PlayerV2>;

export const QaObserverCastleV1 = __t.object("QaObserverCastleV1", {
  castleId: __t.u64(),
  tileKey: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  level: __t.i32(),
  name: __t.string(),
  canonicalUsername: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  portraitAvailable: __t.bool(),
  publicBio: __t.option(__t.string()),
  publicStatus: __t.string(),
});
export type QaObserverCastleV1 = __Infer<typeof QaObserverCastleV1>;

export const QaObserverRealmAggregatesV2 = __t.object("QaObserverRealmAggregatesV2", {
  castleCount: __t.u32(),
  profileCount: __t.u32(),
  foundedCount: __t.u32(),
  activeCount: __t.u32(),
});
export type QaObserverRealmAggregatesV2 = __Infer<typeof QaObserverRealmAggregatesV2>;

export const QaObserverRealmAttestationV2 = __t.object("QaObserverRealmAttestationV2", {
  version: __t.u32(),
  protocolVersion: __t.u32(),
  worldSeed: __t.u32(),
  worldSeedName: __t.string(),
  worldTileCount: __t.u32(),
  worldTileMetaCount: __t.u32(),
  get realm() {
    return QaObserverRealmV2;
  },
  get aggregates() {
    return QaObserverRealmAggregatesV2;
  },
});
export type QaObserverRealmAttestationV2 = __Infer<typeof QaObserverRealmAttestationV2>;

export const QaObserverRealmSnapshotV1 = __t.object("QaObserverRealmSnapshotV1", {
  version: __t.u32(),
  protocolVersion: __t.u32(),
  worldSeed: __t.u32(),
  worldSeedName: __t.string(),
  worldTileCount: __t.u32(),
  worldTileMetaCount: __t.u32(),
  get realm() {
    return QaObserverRealmV1;
  },
  get castles() {
    return __t.array(QaObserverCastleV1);
  },
});
export type QaObserverRealmSnapshotV1 = __Infer<typeof QaObserverRealmSnapshotV1>;

export const QaObserverRealmV1 = __t.object("QaObserverRealmV1", {
  realmId: __t.string(),
  numericSeed: __t.u32(),
  generationVersion: __t.u32(),
  authoritativeRadius: __t.u32(),
  renderRadius: __t.u32(),
  playerCapacity: __t.u32(),
});
export type QaObserverRealmV1 = __Infer<typeof QaObserverRealmV1>;

export const QaObserverRealmV2 = __t.object("QaObserverRealmV2", {
  realmId: __t.string(),
  numericSeed: __t.u32(),
  generationVersion: __t.u32(),
  authoritativeRadius: __t.u32(),
  renderRadius: __t.u32(),
  playerCapacity: __t.u32(),
});
export type QaObserverRealmV2 = __Infer<typeof QaObserverRealmV2>;

export const RealmChatChannelV1 = __t.object("RealmChatChannelV1", {
  channelKey: __t.string(),
  realmId: __t.string(),
  policyVersion: __t.string(),
  mode: __t.string(),
  nextSequence: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type RealmChatChannelV1 = __Infer<typeof RealmChatChannelV1>;

export const RealmChatHistoryPageV1 = __t.object("RealmChatHistoryPageV1", {
  channelKey: __t.string(),
  policyVersion: __t.string(),
  get messages() {
    return __t.array(RealmChatMessageProjectionV1);
  },
  nextBeforeSequence: __t.option(__t.u64()),
  hasMore: __t.bool(),
});
export type RealmChatHistoryPageV1 = __Infer<typeof RealmChatHistoryPageV1>;

export const RealmChatMessageProjectionV1 = __t.object("RealmChatMessageProjectionV1", {
  messageId: __t.string(),
  sequence: __t.u64(),
  senderFid: __t.u64(),
  body: __t.string(),
  sentAtMicros: __t.u64(),
  visibility: __t.string(),
});
export type RealmChatMessageProjectionV1 = __Infer<typeof RealmChatMessageProjectionV1>;

export const RealmChatMessageV1 = __t.object("RealmChatMessageV1", {
  messageId: __t.string(),
  sequence: __t.u64(),
  channelKey: __t.string(),
  senderFid: __t.u64(),
  body: __t.string(),
  sentAt: __t.timestamp(),
  visibility: __t.string(),
  moderatedAt: __t.option(__t.timestamp()),
  moderationCode: __t.option(__t.string()),
});
export type RealmChatMessageV1 = __Infer<typeof RealmChatMessageV1>;

export const RealmChatRateEventV1 = __t.object("RealmChatRateEventV1", {
  eventId: __t.string(),
  fid: __t.u64(),
  acceptedAtMicros: __t.u64(),
  bodyDigest: __t.string(),
});
export type RealmChatRateEventV1 = __Infer<typeof RealmChatRateEventV1>;

export const RealmChatRecentV1 = __t.object("RealmChatRecentV1", {
  sequence: __t.u64(),
  messageId: __t.string(),
  channelKey: __t.string(),
  senderFid: __t.u64(),
  body: __t.string(),
  sentAt: __t.timestamp(),
  visibility: __t.string(),
});
export type RealmChatRecentV1 = __Infer<typeof RealmChatRecentV1>;

export const RealmChatReportV1 = __t.object("RealmChatReportV1", {
  reportOrdinal: __t.u64(),
  reportKey: __t.string(),
  reportId: __t.string(),
  reporterFid: __t.u64(),
  messageId: __t.string(),
  reportedSenderFid: __t.u64(),
  messageSequence: __t.u64(),
  category: __t.string(),
  details: __t.string(),
  contextFirstSequence: __t.u64(),
  contextLastSequence: __t.u64(),
  createdAt: __t.timestamp(),
  status: __t.string(),
  reviewedAt: __t.option(__t.timestamp()),
  resolutionCode: __t.option(__t.string()),
});
export type RealmChatReportV1 = __Infer<typeof RealmChatReportV1>;

export const RealmChatSendReceiptV1 = __t.object("RealmChatSendReceiptV1", {
  operationKey: __t.string(),
  fid: __t.u64(),
  requestKey: __t.string(),
  bodyDigest: __t.string(),
  messageId: __t.string(),
  sequence: __t.u64(),
  createdAt: __t.timestamp(),
});
export type RealmChatSendReceiptV1 = __Infer<typeof RealmChatSendReceiptV1>;

export const RealmChatStatusV1 = __t.object("RealmChatStatusV1", {
  channelKey: __t.string(),
  realmId: __t.string(),
  policyVersion: __t.string(),
  mode: __t.string(),
  recentLimit: __t.u32(),
  historyPageLimit: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type RealmChatStatusV1 = __Infer<typeof RealmChatStatusV1>;

export const RealmEnvironmentV1 = __t.object("RealmEnvironmentV1", {
  realmId: __t.string(),
  environmentEpoch: __t.u64(),
  waterLayoutVersion: __t.u32(),
  seaLevelMilli: __t.i32(),
  sunDirectionXMicro: __t.i32(),
  sunDirectionYMicro: __t.i32(),
  sunDirectionZMicro: __t.i32(),
  updatedAt: __t.timestamp(),
});
export type RealmEnvironmentV1 = __Infer<typeof RealmEnvironmentV1>;

export const RealmForestInstanceV1 = __t.object("RealmForestInstanceV1", {
  treeId: __t.string(),
  realmId: __t.string(),
  tileKey: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  localXMicrounits: __t.i64(),
  localZMicrounits: __t.i64(),
  worldXMicrounits: __t.i64(),
  worldZMicrounits: __t.i64(),
  rotationMilliDegrees: __t.u32(),
  scaleBasisPoints: __t.u32(),
  speciesId: __t.string(),
  habitat: __t.string(),
  layoutVersion: __t.u32(),
});
export type RealmForestInstanceV1 = __Infer<typeof RealmForestInstanceV1>;

export const RealmForestLayoutV1 = __t.object("RealmForestLayoutV1", {
  realmId: __t.string(),
  layoutVersion: __t.u32(),
  policyVersion: __t.string(),
  layoutDigest: __t.string(),
  assetCatalogDigest: __t.string(),
  instanceCount: __t.u32(),
  seededAt: __t.timestamp(),
});
export type RealmForestLayoutV1 = __Infer<typeof RealmForestLayoutV1>;

export const RealmProfileV1 = __t.object("RealmProfileV1", {
  fid: __t.u64(),
  canonicalUsername: __t.option(__t.string()),
  displayName: __t.option(__t.string()),
  pfpUrl: __t.option(__t.string()),
  publicBio: __t.option(__t.string()),
  admittedAt: __t.timestamp(),
  firstAuthenticatedAt: __t.option(__t.timestamp()),
  profileUpdatedAt: __t.timestamp(),
  publicStatus: __t.string(),
  communityStatsVisible: __t.bool(),
  totalSnapBurnedMicros: __t.option(__t.u128()),
  marksEarnedMicros: __t.option(__t.u128()),
  marksSpentMicros: __t.option(__t.u128()),
  marksBalanceMicros: __t.option(__t.u128()),
  marksPolicyVersion: __t.option(__t.string()),
});
export type RealmProfileV1 = __Infer<typeof RealmProfileV1>;

export const RealmV1 = __t.object("RealmV1", {
  realmId: __t.string(),
  publicName: __t.string(),
  seedName: __t.string(),
  numericSeed: __t.u32(),
  generationVersion: __t.u32(),
  authoritativeRadius: __t.u32(),
  renderRadius: __t.u32(),
  playerCapacity: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
});
export type RealmV1 = __Infer<typeof RealmV1>;

export const RealmWaterBodyV1 = __t.object("RealmWaterBodyV1", {
  bodyId: __t.string(),
  realmId: __t.string(),
  regime: __t.string(),
  cellCount: __t.u32(),
  sourceCellKey: __t.string(),
  mouthCellKey: __t.string(),
  surfaceLevelMilli: __t.i32(),
  flowDirectionXq15: __t.i32(),
  flowDirectionZq15: __t.i32(),
  wavePreset: __t.string(),
  ordinal: __t.u32(),
  seed: __t.u32(),
  generationVersion: __t.u32(),
  layoutVersion: __t.u32(),
});
export type RealmWaterBodyV1 = __Infer<typeof RealmWaterBodyV1>;

export const RealmWaterCellV1 = __t.object("RealmWaterCellV1", {
  cellKey: __t.string(),
  realmId: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  regime: __t.string(),
  bodyId: __t.string(),
  depthCells: __t.u32(),
  elevationMilli: __t.i32(),
  surfaceLevelMilli: __t.i32(),
  ring: __t.u32(),
  s: __t.i32(),
  underlyingTileKey: __t.option(__t.string()),
  riverOrdinal: __t.option(__t.u32()),
  riverOrder: __t.option(__t.u32()),
  downstreamWaterCellKey: __t.option(__t.string()),
  flowAccumulation: __t.u32(),
  depthClass: __t.u32(),
  oceanDepth: __t.u32(),
  bankSeed: __t.u32(),
  generationVersion: __t.u32(),
  fogBand: __t.string(),
  layoutVersion: __t.u32(),
});
export type RealmWaterCellV1 = __Infer<typeof RealmWaterCellV1>;

export const RealmWaterLayoutV1 = __t.object("RealmWaterLayoutV1", {
  realmId: __t.string(),
  layoutVersion: __t.u32(),
  policyVersion: __t.string(),
  generationVersion: __t.u32(),
  canonicalLandCellCount: __t.u32(),
  oceanCellCount: __t.u32(),
  lakeCellCount: __t.u32(),
  lakeBodyCount: __t.u32(),
  riverCount: __t.u32(),
  riverCellCount: __t.u32(),
  seaLevelMilli: __t.i32(),
  seaLevelPolicyVersion: __t.string(),
  fogStartDepthCells: __t.u32(),
  fogFullDepthCells: __t.u32(),
  hiddenBufferCells: __t.u32(),
  layoutDigest: __t.string(),
  sourceCommit: __t.string(),
  activated: __t.bool(),
  seededAt: __t.timestamp(),
  activatedAt: __t.option(__t.timestamp()),
});
export type RealmWaterLayoutV1 = __Infer<typeof RealmWaterLayoutV1>;

export const RealmWaterRevisionV1 = __t.object("RealmWaterRevisionV1", {
  realmId: __t.string(),
  revisionVersion: __t.u32(),
  policyVersion: __t.string(),
  baseLayoutVersion: __t.u32(),
  baseLayoutDigest: __t.string(),
  oceanBodyCount: __t.u32(),
  riverBodyCount: __t.u32(),
  enabledBodyCount: __t.u32(),
  oceanCellCount: __t.u32(),
  riverCellCount: __t.u32(),
  enabledCellCount: __t.u32(),
  lakeBodyCount: __t.u32(),
  lakeCellCount: __t.u32(),
  riverWidthCells: __t.u32(),
  navigationFogBoundaryDepthCells: __t.u32(),
  hiddenBufferCells: __t.u32(),
  revisionDigest: __t.string(),
  sourceCommit: __t.string(),
  activated: __t.bool(),
  seededAt: __t.timestamp(),
  activatedAt: __t.option(__t.timestamp()),
});
export type RealmWaterRevisionV1 = __Infer<typeof RealmWaterRevisionV1>;

export const RealmWorkerSystemV1 = __t.object("RealmWorkerSystemV1", {
  realmId: __t.string(),
  policyVersion: __t.string(),
  workersPerCastle: __t.u32(),
  expectedCastleCount: __t.u32(),
  expectedWorkerCount: __t.u32(),
  rosterDigest: __t.string(),
  mode: __t.string(),
  legacyDrainRequired: __t.bool(),
  createdAt: __t.timestamp(),
  activatedAt: __t.option(__t.timestamp()),
});
export type RealmWorkerSystemV1 = __Infer<typeof RealmWorkerSystemV1>;

export const ResourceAccountV1 = __t.object("ResourceAccountV1", {
  fid: __t.u64(),
  castleId: __t.u64(),
  realmId: __t.string(),
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  settledThroughMicros: __t.u64(),
  revision: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type ResourceAccountV1 = __Infer<typeof ResourceAccountV1>;

export const SnapBurnCreditV1 = __t.object("SnapBurnCreditV1", {
  eventKey: __t.string(),
  batchId: __t.string(),
  chainId: __t.u32(),
  tokenContract: __t.string(),
  transactionHash: __t.string(),
  logIndex: __t.u32(),
  burnReference: __t.string(),
  burnMethod: __t.string(),
  senderAddress: __t.string(),
  blockNumber: __t.u64(),
  blockHash: __t.string(),
  amountMicros: __t.u128(),
  attributedFid: __t.u64(),
  attributionPolicyVersion: __t.string(),
  contractCodeHash: __t.string(),
  creditedAt: __t.timestamp(),
});
export type SnapBurnCreditV1 = __Infer<typeof SnapBurnCreditV1>;

export const SnapScanBatchV1 = __t.object("SnapScanBatchV1", {
  batchId: __t.string(),
  cursorKey: __t.string(),
  status: __t.string(),
  previousFinalizedBlock: __t.u64(),
  previousFinalizedBlockHash: __t.string(),
  throughFinalizedBlock: __t.u64(),
  throughFinalizedBlockHash: __t.string(),
  walletSnapshotGeneration: __t.u64(),
  walletSnapshotId: __t.string(),
  walletAttributionCount: __t.u32(),
  expectedCredits: __t.u32(),
  expectedMicros: __t.u128(),
  appliedCredits: __t.u32(),
  appliedMicros: __t.u128(),
  proxyCodeHash: __t.string(),
  implementationAddress: __t.string(),
  implementationCodeHash: __t.string(),
  startedAt: __t.timestamp(),
  finalizedAt: __t.option(__t.timestamp()),
});
export type SnapScanBatchV1 = __Infer<typeof SnapScanBatchV1>;

export const SnapScanCursorV1 = __t.object("SnapScanCursorV1", {
  cursorKey: __t.string(),
  chainId: __t.u32(),
  tokenContract: __t.string(),
  policyVersion: __t.string(),
  deploymentStartBlock: __t.u64(),
  lastFinalizedBlock: __t.u64(),
  lastFinalizedBlockHash: __t.string(),
  proxyCodeHash: __t.string(),
  implementationAddress: __t.string(),
  implementationCodeHash: __t.string(),
  walletSnapshotGeneration: __t.u64(),
  walletSnapshotId: __t.string(),
  scannedAt: __t.timestamp(),
});
export type SnapScanCursorV1 = __Infer<typeof SnapScanCursorV1>;

export const StoneExpeditionIdempotencyV1 = __t.object("StoneExpeditionIdempotencyV1", {
  requestKey: __t.string(),
  fid: __t.u64(),
  siteId: __t.string(),
  expeditionId: __t.string(),
  createdAt: __t.timestamp(),
});
export type StoneExpeditionIdempotencyV1 = __Infer<typeof StoneExpeditionIdempotencyV1>;

export const StoneExpeditionScheduleV1 = __t.object("StoneExpeditionScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  stage: __t.string(),
});
export type StoneExpeditionScheduleV1 = __Infer<typeof StoneExpeditionScheduleV1>;

export const StoneExpeditionV1 = __t.object("StoneExpeditionV1", {
  expeditionId: __t.string(),
  fid: __t.u64(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  accruedStone: __t.u64(),
  creditedStone: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type StoneExpeditionV1 = __Infer<typeof StoneExpeditionV1>;

export const StoneNodeOccupationV1 = __t.object("StoneNodeOccupationV1", {
  siteId: __t.string(),
  originCastleId: __t.u64(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
});
export type StoneNodeOccupationV1 = __Infer<typeof StoneNodeOccupationV1>;

export const StoneSiteV1 = __t.object("StoneSiteV1", {
  siteId: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  tier: __t.u32(),
  active: __t.bool(),
});
export type StoneSiteV1 = __Infer<typeof StoneSiteV1>;

export const WalletAttributionSnapshotV1 = __t.object("WalletAttributionSnapshotV1", {
  snapshotKey: __t.string(),
  generation: __t.u64(),
  snapshotId: __t.string(),
  policyVersion: __t.string(),
  attributionCount: __t.u32(),
  snapshotAt: __t.timestamp(),
});
export type WalletAttributionSnapshotV1 = __Infer<typeof WalletAttributionSnapshotV1>;

export const WoodExpeditionIdempotencyV1 = __t.object("WoodExpeditionIdempotencyV1", {
  requestKey: __t.string(),
  fid: __t.u64(),
  siteId: __t.string(),
  expeditionId: __t.string(),
  createdAt: __t.timestamp(),
});
export type WoodExpeditionIdempotencyV1 = __Infer<typeof WoodExpeditionIdempotencyV1>;

export const WoodExpeditionScheduleV1 = __t.object("WoodExpeditionScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  stage: __t.string(),
});
export type WoodExpeditionScheduleV1 = __Infer<typeof WoodExpeditionScheduleV1>;

export const WoodExpeditionV1 = __t.object("WoodExpeditionV1", {
  expeditionId: __t.string(),
  fid: __t.u64(),
  originCastleId: __t.u64(),
  siteId: __t.string(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
  settledThroughMicros: __t.u64(),
  accruedWood: __t.u64(),
  creditedWood: __t.u64(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WoodExpeditionV1 = __Infer<typeof WoodExpeditionV1>;

export const WoodNodeOccupationV1 = __t.object("WoodNodeOccupationV1", {
  siteId: __t.string(),
  originCastleId: __t.u64(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnsAtMicros: __t.u64(),
});
export type WoodNodeOccupationV1 = __Infer<typeof WoodNodeOccupationV1>;

export const WoodSiteV1 = __t.object("WoodSiteV1", {
  siteId: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  tier: __t.u32(),
  active: __t.bool(),
});
export type WoodSiteV1 = __Infer<typeof WoodSiteV1>;

export const WorkerAssignmentScheduleV1 = __t.object("WorkerAssignmentScheduleV1", {
  scheduleId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  assignmentId: __t.string(),
  workerId: __t.string(),
  timelineRevision: __t.u32(),
  stage: __t.string(),
});
export type WorkerAssignmentScheduleV1 = __Infer<typeof WorkerAssignmentScheduleV1>;

export const WorkerAssignmentV1 = __t.object("WorkerAssignmentV1", {
  assignmentId: __t.string(),
  workerId: __t.string(),
  fid: __t.u64(),
  originCastleId: __t.u64(),
  resourceKind: __t.string(),
  siteId: __t.string(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  returnStartedAtMicros: __t.option(__t.u64()),
  returnsAtMicros: __t.u64(),
  routeSteps: __t.u32(),
  returnStartProgressBasisPoints: __t.u32(),
  settledThroughMicros: __t.u64(),
  accruedAmount: __t.u64(),
  materializedAmount: __t.u64(),
  timelineRevision: __t.u32(),
  policyVersion: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type WorkerAssignmentV1 = __Infer<typeof WorkerAssignmentV1>;

export const WorkerCommandIdempotencyV1 = __t.object("WorkerCommandIdempotencyV1", {
  requestKey: __t.string(),
  fid: __t.u64(),
  workerId: __t.option(__t.string()),
  commandKind: __t.string(),
  resourceKind: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  assignmentId: __t.option(__t.string()),
  resultRevision: __t.u64(),
  createdAt: __t.timestamp(),
});
export type WorkerCommandIdempotencyV1 = __Infer<typeof WorkerCommandIdempotencyV1>;

export const WorkerNodeOccupationV1 = __t.object("WorkerNodeOccupationV1", {
  nodeKey: __t.string(),
  resourceKind: __t.string(),
  siteId: __t.string(),
  workerId: __t.string(),
  workerOrdinal: __t.u32(),
  originCastleId: __t.u64(),
  phase: __t.string(),
  startedAtMicros: __t.u64(),
  arrivesAtMicros: __t.u64(),
  gatheringEndsAtMicros: __t.u64(),
  timelineRevision: __t.u32(),
});
export type WorkerNodeOccupationV1 = __Infer<typeof WorkerNodeOccupationV1>;

export const WorkerPrivateV1 = __t.object("WorkerPrivateV1", {
  workerId: __t.string(),
  ordinal: __t.u32(),
  status: __t.string(),
  resourceKind: __t.option(__t.string()),
  siteId: __t.option(__t.string()),
  accruedAmount: __t.u64(),
  materializedAmount: __t.u64(),
  availableAmount: __t.u64(),
  observedAtMicros: __t.u64(),
  revision: __t.u64(),
});
export type WorkerPrivateV1 = __Infer<typeof WorkerPrivateV1>;

export const WorldTile = __t.object("WorldTile", {
  key: __t.string(),
  q: __t.i32(),
  r: __t.i32(),
  biome: __t.string(),
  terrainSeed: __t.u32(),
  occupantCastleId: __t.option(__t.u64()),
});
export type WorldTile = __Infer<typeof WorldTile>;

export const WorldTileMetaV1 = __t.object("WorldTileMetaV1", {
  tileKey: __t.string(),
  realmId: __t.string(),
  s: __t.i32(),
  ring: __t.u32(),
  sector: __t.u32(),
  terrainKind: __t.string(),
  passable: __t.bool(),
  movementCost: __t.u32(),
  staticContentKind: __t.string(),
  generationVersion: __t.u32(),
});
export type WorldTileMetaV1 = __Infer<typeof WorldTileMetaV1>;

