// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  siteId: __t.string().primaryKey().name("site_id"),
  originCastleId: __t.u64().name("origin_castle_id"),
  phase: __t.string(),
  startedAtMicros: __t.u64().name("started_at_micros"),
  arrivesAtMicros: __t.u64().name("arrives_at_micros"),
  gatheringEndsAtMicros: __t.u64().name("gathering_ends_at_micros"),
  returnsAtMicros: __t.u64().name("returns_at_micros"),
});
