// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scheduleId: __t.u64().primaryKey().name("schedule_id"),
  scheduledAt: __t.scheduleAt().name("scheduled_at"),
  assignmentId: __t.string().name("assignment_id"),
  workerId: __t.string().name("worker_id"),
  timelineRevision: __t.u32().name("timeline_revision"),
  stage: __t.string(),
});
