// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  tileKey: __t.string().primaryKey().name("tile_key"),
  realmId: __t.string().name("realm_id"),
  s: __t.i32(),
  ring: __t.u32(),
  sector: __t.u32(),
  terrainKind: __t.string().name("terrain_kind"),
  passable: __t.bool(),
  movementCost: __t.u32().name("movement_cost"),
  staticContentKind: __t.string().name("static_content_kind"),
  generationVersion: __t.u32().name("generation_version"),
});
