import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { planKeep04DressingSource } from '../src/components/keep04/planKeep04DressingSource';
import type { VoxelSurfacePlan } from '../src/components/realm/voxelSurfaceMesh';

const root = resolve(import.meta.dirname, '..');
const output = resolve(root, 'src/components/keep04/keep04DressingPlans.generated.ts');
const inputs = [
  'scripts/generate-keep04-voxel-dressing.ts',
  'src/components/keep04/planKeep04DressingSource.ts',
  'src/components/keep04/keep04VisualProfile.ts',
  'src/components/realm/voxelSurfaceMesh.ts',
];
const canonical = (text: string) => text.replace(/\r\n/g, '\n');

function literal(plan: VoxelSurfacePlan) {
  const { quads, ...metadata } = plan;
  return `Object.freeze({\n    quads: Object.freeze([\n`
    + quads.map(quad => `      Object.freeze(${JSON.stringify(quad)}),`).join('\n')
    + `\n    ]),\n`
    + Object.entries(metadata).map(([name, value]) => `    ${name}: ${JSON.stringify(value)},`).join('\n')
    + '\n  })';
}

async function main() {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== '--check')) throw new Error('Only --check is accepted.');
  const digest = createHash('sha256');
  for (const input of inputs) digest.update(input).update('\0').update(canonical(await readFile(resolve(root, input), 'utf8'))).update('\0');
  const source = '// Generated by scripts/generate-keep04-voxel-dressing.ts; do not edit.\n'
    + '// Provenance: offline planVoxelSurface planning; runtime createVoxelSurfaceMeshData emission.\n'
    + "import type { VoxelSurfacePlan } from '../realm/voxelSurfaceMesh';\n"
    + "import type { Quality04 } from './keep04VisualProfile';\n\n"
    + `export const KEEP04_DRESSING_PLAN_SOURCE_SHA256 = '${digest.digest('hex')}';\n`
    + 'export const KEEP04_DRESSING_PLANS: Readonly<Record<Quality04, VoxelSurfacePlan>> = Object.freeze({\n'
    + (['high', 'balanced', 'reduced'] as const).map(quality => `  ${quality}: ${literal(planKeep04DressingSource(quality))},`).join('\n')
    + '\n});\n';
  if (args[0] === '--check') {
    const observed = await readFile(output, 'utf8').catch(error => {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null;
      throw error;
    });
    if (observed === null || canonical(observed) !== source) throw new Error('Keep04 voxel dressing plans are missing or stale; run the generator.');
    console.log('Keep04 voxel dressing plans are current.');
  } else {
    await writeFile(output, source, 'utf8');
    console.log('Generated Keep04 voxel dressing plans with the genuine bounded planner.');
  }
}
await main();
