export const GENESIS_WORLD_PUBLISH_STAGE: Readonly<Record<string, string>>;
export const PRODUCTION_V11_TABLE_PRODUCT_TYPE_REFS: Readonly<Record<string, number>>;
export const RESOURCE_PUBLISH_ROLLOUT_STAGE: Readonly<Record<string, string>>;
export const WORKER_PUBLISH_ROLLOUT_STAGE: Readonly<Record<string, string>>;
export const WORKER_V12_TABLE_CONTRACTS: Readonly<Record<string, Readonly<{
  productTypeRef: number;
  access: string;
  fields: readonly string[];
}>>>;

export function alphaV8AggregateChildArguments(...args: any[]): any;
export function alphaV10AggregateChildArguments(...args: any[]): any;
export function alphaV12AggregateChildArguments(...args: any[]): any;
export function canonicalSchemaDescribeChildArguments(...args: any[]): any;
export function createPrivatePublishSnapshot(...args: any[]): any;
export function parseCanonicalSchemaDescription(...args: any[]): any;
export function parseMigrationProofReceipt(...args: any[]): any;
export function parsePublishArguments(...args: any[]): any;
export function publishChildEnvironment(...args: any[]): any;
export function publishModule(...args: any[]): any;
export function readFoundedPublishExpectations(...args: any[]): any;
export function requireCanonicalPublishCoordinates(...args: any[]): any;
export function runCurrentAdditiveMigrationProof(...args: any[]): any;
export function validateIssuerDeployment(...args: any[]): any;
export function verifyCanonicalDatabaseList(...args: any[]): any;
export function verifyFreshAlphaStatusV8Aggregate(...args: any[]): any;
export function verifyFreshAlphaStatusV10Aggregate(...args: any[]): any;
export function verifyFreshAlphaStatusV12Aggregate(...args: any[]): any;
export function verifyFreshProductionV11Schema(...args: any[]): any;
export function verifyFreshFoundedProtocolV3Aggregate(...args: any[]): any;
export function verifyFreshResourceProtocolV4PrebackfillAggregate(...args: any[]): any;
export function verifyFreshResourceProtocolV4ReadyAggregate(...args: any[]): any;
export function verifyMigrationArtifactReceipt(...args: any[]): any;
export function verifyPinnedCliAttestation(...args: any[]): any;
export function verifyPostPublishAlphaStatusV8Aggregate(...args: any[]): any;
export function verifyPostPublishAlphaStatusV10Aggregate(...args: any[]): any;
export function verifyPostPublishAlphaStatusV12Aggregate(...args: any[]): any;
export function verifyPostPublishFoundedProtocolV3Aggregate(...args: any[]): any;
export function verifyPostPublishProductionV12Schema(...args: any[]): any;
export function verifyPostPublishResourceProtocolV4PrebackfillAggregate(...args: any[]): any;
export function verifyPostPublishResourceProtocolV4ReadyAggregate(...args: any[]): any;
export function verifyPostPublishResourcePublicationCheckpoints(...args: any[]): any;
export function verifyPrivacySafeAlphaStatusV8Output(...args: any[]): any;
export function verifyPrivacySafeAlphaStatusV10Output(...args: any[]): any;
export function verifyPrivacySafeAlphaStatusV12Output(...args: any[]): any;
export function verifyEmptyAlphaStatusV12(...args: any[]): any;
export function verifyExactProductionV11Schema(...args: any[]): any;
export function verifyExactProductionV12Schema(...args: any[]): any;
