// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PtrGreaterRealmComponentImportV1,
} from "./types";

export default {
  ptrReleaseVersion: __t.string(),
  ptrModuleIdentity: __t.string(),
  atlasId: __t.string(),
  importEpoch: __t.u64(),
  get rows() {
    return __t.array(PtrGreaterRealmComponentImportV1);
  },
};
