// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Gameplay04WorkerCommandResultV1,
} from "./types";

export const params = {
  sequence: __t.u64(),
  requestKey: __t.string(),
  expectedRevision: __t.u64(),
  policyVersion: __t.string(),
  expectedAtlasRevision: __t.u64(),
  workerOrdinal: __t.u32(),
  locationId: __t.string(),
  resource: __t.string(),
  gatheringDurationMicros: __t.i64(),
};
export const returnType = Gameplay04WorkerCommandResultV1