// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PtrGreaterRealmWindowV1,
} from "./types";

export const params = {
  centerQ: __t.i32(),
  centerR: __t.i32(),
  radius: __t.u32(),
  expectedRevision: __t.u64(),
};
export const returnType = PtrGreaterRealmWindowV1