// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  PtrGreaterRealmResourceLocationBatchV1,
} from "./types";

export const params = {
  expectedRevision: __t.u64(),
  chunkHandles: __t.array(__t.string()),
};
export const returnType = PtrGreaterRealmResourceLocationBatchV1