// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Gameplay04ConstructionCostInputV1,
  Gameplay04ConstructionCommandResultV1,
} from "./types";

export const params = {
  sequence: __t.u64(),
  requestKey: __t.string(),
  expectedRevision: __t.u64(),
  expectedAtlasRevision: __t.u64(),
  policyVersion: __t.string(),
  layoutDigest: __t.string(),
  kind: __t.string(),
  targetLevel: __t.u32(),
  x: __t.i64(),
  z: __t.i64(),
  rotation: __t.u32(),
  get expectedCost() {
    return Gameplay04ConstructionCostInputV1;
  },
  expectedDurationMicros: __t.i64(),
};
export const returnType = Gameplay04ConstructionCommandResultV1