/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workerd.toml --include-runtime=false test-workerd/worker-configuration.d.ts` (hash: e91027bbabe257795c6e2a363ee4a698)
interface __BaseEnv_Env {
	RECOVERY_LEDGER: DurableObjectNamespace<import("./worker").ReleaseRecoveryAuthorizationLedger>;
	RECOVERY_LEDGER_V2: DurableObjectNamespace<import("./worker").ReleaseRecoveryAuthorizationLedgerV2>;
	RECOVERY_GATEWAY_TEST_SIGNER: Service<typeof import("./worker").RecoveryGatewayTestSigner>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ReleaseRecoveryAuthorizationLedger" | "ReleaseRecoveryAuthorizationLedgerV2";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
