/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workerd.toml --include-runtime=false test-workerd/worker-configuration.d.ts` (hash: c65d63081114095bbc4af86ae57d9003)
interface __BaseEnv_Env {
	RECOVERY_LEDGER: DurableObjectNamespace<import("./worker").ReleaseRecoveryAuthorizationLedger>;
	RECOVERY_LEDGER_V2: DurableObjectNamespace<import("./worker").ReleaseRecoveryAuthorizationLedgerV2>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ReleaseRecoveryAuthorizationLedger" | "ReleaseRecoveryAuthorizationLedgerV2";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
