/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.workerd.toml --include-runtime=false test-workerd/worker-configuration.d.ts` (hash: e30e2d7632be314403b3b534e9e8864d)
interface __BaseEnv_Env {
	RECOVERY_LEDGER: DurableObjectNamespace<import("./worker").ReleaseRecoveryAuthorizationLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
		durableNamespaces: "ReleaseRecoveryAuthorizationLedger";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
