// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as AdminGetGreaterRealmStatusV1Procedure from "../admin_get_greater_realm_status_v_1_procedure";
import * as GetPtrOwnerStatusV1Procedure from "../get_ptr_owner_status_v_1_procedure";
import * as GetRealmAtlasBootstrapV1Procedure from "../get_realm_atlas_bootstrap_v_1_procedure";
import * as GetRealmAtlasChunkV1Procedure from "../get_realm_atlas_chunk_v_1_procedure";
import * as GetRealmAtlasResourceLocationsV1Procedure from "../get_realm_atlas_resource_locations_v_1_procedure";
import * as GetRealmAtlasWindowV1Procedure from "../get_realm_atlas_window_v_1_procedure";
import * as PlanRealmRouteV1Procedure from "../plan_realm_route_v_1_procedure";

export type AdminGetGreaterRealmStatusV1Args = __Infer<typeof AdminGetGreaterRealmStatusV1Procedure.params>;
export type AdminGetGreaterRealmStatusV1Result = __Infer<typeof AdminGetGreaterRealmStatusV1Procedure.returnType>;
export type GetPtrOwnerStatusV1Args = __Infer<typeof GetPtrOwnerStatusV1Procedure.params>;
export type GetPtrOwnerStatusV1Result = __Infer<typeof GetPtrOwnerStatusV1Procedure.returnType>;
export type GetRealmAtlasBootstrapV1Args = __Infer<typeof GetRealmAtlasBootstrapV1Procedure.params>;
export type GetRealmAtlasBootstrapV1Result = __Infer<typeof GetRealmAtlasBootstrapV1Procedure.returnType>;
export type GetRealmAtlasChunkV1Args = __Infer<typeof GetRealmAtlasChunkV1Procedure.params>;
export type GetRealmAtlasChunkV1Result = __Infer<typeof GetRealmAtlasChunkV1Procedure.returnType>;
export type GetRealmAtlasResourceLocationsV1Args = __Infer<typeof GetRealmAtlasResourceLocationsV1Procedure.params>;
export type GetRealmAtlasResourceLocationsV1Result = __Infer<typeof GetRealmAtlasResourceLocationsV1Procedure.returnType>;
export type GetRealmAtlasWindowV1Args = __Infer<typeof GetRealmAtlasWindowV1Procedure.params>;
export type GetRealmAtlasWindowV1Result = __Infer<typeof GetRealmAtlasWindowV1Procedure.returnType>;
export type PlanRealmRouteV1Args = __Infer<typeof PlanRealmRouteV1Procedure.params>;
export type PlanRealmRouteV1Result = __Infer<typeof PlanRealmRouteV1Procedure.returnType>;

