// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AdminBeginGreaterRealmVerificationV1Reducer from "../admin_begin_greater_realm_verification_v_1_reducer";
import AdminFinalizeGreaterRealmReleaseV1Reducer from "../admin_finalize_greater_realm_release_v_1_reducer";
import AdminImportGreaterRealmChunkV1Reducer from "../admin_import_greater_realm_chunk_v_1_reducer";
import AdminImportGreaterRealmComponentsV1Reducer from "../admin_import_greater_realm_components_v_1_reducer";
import AdminImportGreaterRealmRegionsV1Reducer from "../admin_import_greater_realm_regions_v_1_reducer";
import AdminProvisionPtrOwnerV1Reducer from "../admin_provision_ptr_owner_v_1_reducer";
import AdminStageGreaterRealmReleaseV1Reducer from "../admin_stage_greater_realm_release_v_1_reducer";
import AdminSuspendPtrOwnerV1Reducer from "../admin_suspend_ptr_owner_v_1_reducer";
import AdminVerifyGreaterRealmBatchV1Reducer from "../admin_verify_greater_realm_batch_v_1_reducer";

export type AdminBeginGreaterRealmVerificationV1Params = __Infer<typeof AdminBeginGreaterRealmVerificationV1Reducer>;
export type AdminFinalizeGreaterRealmReleaseV1Params = __Infer<typeof AdminFinalizeGreaterRealmReleaseV1Reducer>;
export type AdminImportGreaterRealmChunkV1Params = __Infer<typeof AdminImportGreaterRealmChunkV1Reducer>;
export type AdminImportGreaterRealmComponentsV1Params = __Infer<typeof AdminImportGreaterRealmComponentsV1Reducer>;
export type AdminImportGreaterRealmRegionsV1Params = __Infer<typeof AdminImportGreaterRealmRegionsV1Reducer>;
export type AdminProvisionPtrOwnerV1Params = __Infer<typeof AdminProvisionPtrOwnerV1Reducer>;
export type AdminStageGreaterRealmReleaseV1Params = __Infer<typeof AdminStageGreaterRealmReleaseV1Reducer>;
export type AdminSuspendPtrOwnerV1Params = __Infer<typeof AdminSuspendPtrOwnerV1Reducer>;
export type AdminVerifyGreaterRealmBatchV1Params = __Infer<typeof AdminVerifyGreaterRealmBatchV1Reducer>;

