// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  atlasId: __t.string(),
  publicReleaseId: __t.string(),
  publicApprovalReceiptId: __t.string(),
  sourceCommit: __t.string(),
  generatorVersion: __t.string(),
  sourceFormatVersion: __t.string(),
  livingWorldVersion: __t.string(),
  runtimePartitionVersion: __t.string(),
  rendererContractVersion: __t.string(),
  expectedRegionCount: __t.u32(),
  expectedComponentCount: __t.u32(),
  expectedChunkCount: __t.u32(),
  expectedCellCount: __t.u32(),
  expectedSlotCount: __t.u32(),
  expectedResourceNodeCount: __t.u32(),
  expectedReleaseSha256: __t.string(),
  importEpoch: __t.u64(),
  releaseHeaderJson: __t.string(),
};
