// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  atlasId: __t.string(),
  importEpoch: __t.u64(),
  publicApprovalReceiptId: __t.string(),
  expectedReleaseSha256: __t.string(),
  expectedVerificationDigest: __t.string(),
  publicName: __t.string(),
};
