// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  fid: __t.u64(),
  note: __t.string(),
  canonicalUsername: __t.string(),
  displayName: __t.option(__t.string()),
  pfpUrl: __t.string(),
  publicBio: __t.option(__t.string()),
  profilePolicyVersion: __t.string(),
};
