// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fid: __t.u64().primaryKey(),
  enabled: __t.bool(),
  authEpoch: __t.u32().name("auth_epoch"),
  invitedAt: __t.timestamp().name("invited_at"),
  invitedBy: __t.string().name("invited_by"),
  note: __t.string(),
});
