// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  acceptanceKey: __t.string().primaryKey().name("acceptance_key"),
  fid: __t.u64(),
  termsVersion: __t.string().name("terms_version"),
  acceptedAt: __t.timestamp().name("accepted_at"),
});
