// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  castleId: __t.u64().primaryKey().name("castle_id"),
  ownerFid: __t.u64().name("owner_fid"),
  tileKey: __t.string().name("tile_key"),
  q: __t.i32(),
  r: __t.i32(),
  level: __t.i32(),
  name: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
