// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Gameplay04AssignmentV1,
  Gameplay04ReturnOutcomeV1,
} from "./types";


export default __t.row({
  workerId: __t.string().primaryKey().name("worker_id"),
  keepId: __t.string().name("keep_id"),
  ordinal: __t.u32(),
  assignmentRevision: __t.u64().name("assignment_revision"),
  get assignment() {
    return __t.option(Gameplay04AssignmentV1);
  },
  get lastReturn() {
    return __t.option(Gameplay04ReturnOutcomeV1).name("last_return");
  },
});
