// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  receiptId: __t.string().primaryKey().name("receipt_id"),
  keepId: __t.string().name("keep_id"),
  sequence: __t.u64(),
  requestKey: __t.string().name("request_key"),
  fingerprint: __t.string(),
  resultRevision: __t.u64().name("result_revision"),
});
