// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  buildingId: __t.string().primaryKey().name("building_id"),
  keepId: __t.string().name("keep_id"),
  kind: __t.string(),
  x: __t.i64(),
  z: __t.i64(),
  rotation: __t.u32(),
  completedLevel: __t.u32().name("completed_level"),
  revision: __t.u64(),
});
