// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Gameplay04CostV1,
} from "./types";


export default __t.row({
  keepId: __t.string().primaryKey().name("keep_id"),
  projectRevision: __t.u64().name("project_revision"),
  buildingId: __t.string().name("building_id"),
  targetLevel: __t.u32().name("target_level"),
  startedAtMicros: __t.i64().name("started_at_micros"),
  completesAtMicros: __t.i64().name("completes_at_micros"),
  get cost() {
    return Gameplay04CostV1;
  },
  durationMicros: __t.i64().name("duration_micros"),
  policyVersion: __t.string().name("policy_version"),
  layoutDigest: __t.string().name("layout_digest"),
});
