// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.string().primaryKey().name("node_id"),
  keepId: __t.string().name("keep_id"),
  workerId: __t.string().name("worker_id"),
  assignmentRevision: __t.u64().name("assignment_revision"),
});
