// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  keepId: __t.string().primaryKey().name("keep_id"),
  databaseIdentity: __t.string().name("database_identity"),
  ownerFid: __t.u64().name("owner_fid"),
  atlasId: __t.string().name("atlas_id"),
  atlasRevision: __t.u64().name("atlas_revision"),
  anchorCellKey: __t.string().name("anchor_cell_key"),
  policyVersion: __t.string().name("policy_version"),
  revision: __t.u64(),
  lastAcceptedSequence: __t.u64().name("last_accepted_sequence"),
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  createdAtMicros: __t.i64().name("created_at_micros"),
});
