// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cellKey: __t.string().primaryKey().name("cell_key"),
  atlasId: __t.string().name("atlas_id"),
  regionId: __t.string().name("region_id"),
  castleId: __t.u64().name("castle_id"),
  atlasRevision: __t.u64().name("atlas_revision"),
  occupiedAt: __t.timestamp().name("occupied_at"),
});
