// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slotId: __t.string().primaryKey().name("slot_id"),
  ownerFid: __t.u64().name("owner_fid"),
  castleId: __t.u64().name("castle_id"),
  atlasId: __t.string().name("atlas_id"),
  activationId: __t.string().name("activation_id"),
  state: __t.string(),
  claimKind: __t.string().name("claim_kind"),
  allocationSequence: __t.u64().name("allocation_sequence"),
  plannedAt: __t.timestamp().name("planned_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
  legacySlotId: __t.option(__t.u32()).name("legacy_slot_id"),
  legacyClaimedAt: __t.option(__t.timestamp()).name("legacy_claimed_at"),
  legacyGenerationVersion: __t.option(__t.u32()).name("legacy_generation_version"),
  legacyTileKey: __t.option(__t.string()).name("legacy_tile_key"),
  legacyQ: __t.option(__t.i32()).name("legacy_q"),
  legacyR: __t.option(__t.i32()).name("legacy_r"),
});
