// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  activationId: __t.string().primaryKey().name("activation_id"),
  atlasId: __t.string().name("atlas_id"),
  quietEpoch: __t.u64().name("quiet_epoch"),
  mode: __t.string(),
  snapshotCastleCount: __t.u32().name("snapshot_castle_count"),
  snapshotWorkerCount: __t.u32().name("snapshot_worker_count"),
  snapshotResourceAccountCount: __t.u32().name("snapshot_resource_account_count"),
  snapshotMarkAccountCount: __t.u32().name("snapshot_mark_account_count"),
  snapshotInnerKeepBuildingCount: __t.u32().name("snapshot_inner_keep_building_count"),
  snapshotClaimCount: __t.u32().name("snapshot_claim_count"),
  snapshotOccupancyCount: __t.u32().name("snapshot_occupancy_count"),
  snapshotCastleDigest: __t.string().name("snapshot_castle_digest"),
  snapshotWorkerDigest: __t.string().name("snapshot_worker_digest"),
  snapshotResourceDigest: __t.string().name("snapshot_resource_digest"),
  snapshotMarksDigest: __t.string().name("snapshot_marks_digest"),
  snapshotInnerKeepDigest: __t.string().name("snapshot_inner_keep_digest"),
  snapshotScheduleDigest: __t.string().name("snapshot_schedule_digest"),
  topologySnapshotDigest: __t.string().name("topology_snapshot_digest"),
  relocationPlanDigest: __t.string().name("relocation_plan_digest"),
  nextAllocationSequence: __t.u64().name("next_allocation_sequence"),
  postCanaryFoundingCount: __t.u32().name("post_canary_founding_count"),
  postCanaryDispatchCount: __t.u32().name("post_canary_dispatch_count"),
  actorSubject: __t.string().name("actor_subject"),
  preparedAt: __t.timestamp().name("prepared_at"),
  drainingAt: __t.option(__t.timestamp()).name("draining_at"),
  frozenAt: __t.option(__t.timestamp()).name("frozen_at"),
  plannedAt: __t.option(__t.timestamp()).name("planned_at"),
  canaryAt: __t.option(__t.timestamp()).name("canary_at"),
  activatedAt: __t.option(__t.timestamp()).name("activated_at"),
  haltedAt: __t.option(__t.timestamp()).name("halted_at"),
  rolledBackAt: __t.option(__t.timestamp()).name("rolled_back_at"),
});
