// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chunkHandle: __t.string().primaryKey().name("chunk_handle"),
  atlasId: __t.string().name("atlas_id"),
  chunkCoordKey: __t.string().name("chunk_coord_key"),
  importOrdinal: __t.u32().name("import_ordinal"),
  binQ: __t.i32().name("bin_q"),
  binR: __t.i32().name("bin_r"),
  firstCellOrdinal: __t.u32().name("first_cell_ordinal"),
  coreCellCount: __t.u32().name("core_cell_count"),
  apronCellCount: __t.u32().name("apron_cell_count"),
  lod0CellCount: __t.u32().name("lod_0_cell_count"),
  lod1CellCount: __t.u32().name("lod_1_cell_count"),
  lod2CellCount: __t.u32().name("lod_2_cell_count"),
  lod3CellCount: __t.u32().name("lod_3_cell_count"),
  payloadSha256: __t.string().name("payload_sha_256"),
  payloadJson: __t.string().name("payload_json"),
  importedAt: __t.timestamp().name("imported_at"),
});
