// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  componentKey: __t.string().primaryKey().name("component_key"),
  atlasId: __t.string().name("atlas_id"),
  componentOrdinal: __t.u32().name("component_ordinal"),
  regionMask: __t.u32().name("region_mask"),
  rootCellKey: __t.string().name("root_cell_key"),
  expectedCellCount: __t.u32().name("expected_cell_count"),
  importedCellCount: __t.u32().name("imported_cell_count"),
  verifiedCellCount: __t.u32().name("verified_cell_count"),
  verifiedRegionMask: __t.u32().name("verified_region_mask"),
  verifiedMaxRouteDepth: __t.u32().name("verified_max_route_depth"),
  maxRouteDepth: __t.u32().name("max_route_depth"),
  expectedSlotCount: __t.u32().name("expected_slot_count"),
  importedSlotCount: __t.u32().name("imported_slot_count"),
  expectedFoodNodeCount: __t.u32().name("expected_food_node_count"),
  importedFoodNodeCount: __t.u32().name("imported_food_node_count"),
  expectedWoodNodeCount: __t.u32().name("expected_wood_node_count"),
  importedWoodNodeCount: __t.u32().name("imported_wood_node_count"),
  expectedStoneNodeCount: __t.u32().name("expected_stone_node_count"),
  importedStoneNodeCount: __t.u32().name("imported_stone_node_count"),
  expectedGoldNodeCount: __t.u32().name("expected_gold_node_count"),
  importedGoldNodeCount: __t.u32().name("imported_gold_node_count"),
  verifiedSlotCount: __t.u32().name("verified_slot_count"),
  verifiedFoodNodeCount: __t.u32().name("verified_food_node_count"),
  verifiedWoodNodeCount: __t.u32().name("verified_wood_node_count"),
  verifiedStoneNodeCount: __t.u32().name("verified_stone_node_count"),
  verifiedGoldNodeCount: __t.u32().name("verified_gold_node_count"),
  componentSha256: __t.string().name("component_sha_256"),
  verificationPhase: __t.string().name("verification_phase"),
  verificationDigest: __t.string().name("verification_digest"),
  regionVerificationJson: __t.string().name("region_verification_json"),
  active: __t.bool(),
});
