// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.string().primaryKey().name("node_id"),
  releaseOrdinal: __t.u32().name("release_ordinal"),
  atlasId: __t.string().name("atlas_id"),
  locationId: __t.string().name("location_id"),
  cellKey: __t.string().name("cell_key"),
  regionId: __t.string().name("region_id"),
  componentKey: __t.string().name("component_key"),
  resourceKind: __t.string().name("resource_kind"),
  tier: __t.u32(),
  nodeOrdinal: __t.u32().name("node_ordinal"),
  allocationRank: __t.u32().name("allocation_rank"),
  legacyCatalogId: __t.option(__t.string()).name("legacy_catalog_id"),
  policyVersion: __t.string().name("policy_version"),
  active: __t.bool(),
});
