// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  slotId: __t.string().primaryKey().name("slot_id"),
  releaseOrdinal: __t.u32().name("release_ordinal"),
  atlasId: __t.string().name("atlas_id"),
  cellKey: __t.string().name("cell_key"),
  regionId: __t.string().name("region_id"),
  componentKey: __t.string().name("component_key"),
  legacySlotId: __t.option(__t.u32()).name("legacy_slot_id"),
  tier: __t.u32(),
  regionOrderRank: __t.u32().name("region_order_rank"),
  allocationRank: __t.u32().name("allocation_rank"),
  active: __t.bool(),
});
