// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.1 (commit 052c83fe984a4c4eb7bb4f9afa5c6b1903891d87).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptAlphaTermsV1Reducer from "./accept_alpha_terms_v_1_reducer";
import AdminAdmitFounderForAccessRequestV2Reducer from "./admin_admit_founder_for_access_request_v_2_reducer";
import AdminAdmitFounderV1Reducer from "./admin_admit_founder_v_1_reducer";
import AdminAllowFidReducer from "./admin_allow_fid_reducer";
import AdminAllowFidForAccessRequestV1Reducer from "./admin_allow_fid_for_access_request_v_1_reducer";
import AdminBeginGreaterRealmVerificationV1Reducer from "./admin_begin_greater_realm_verification_v_1_reducer";
import AdminBumpAuthEpochReducer from "./admin_bump_auth_epoch_reducer";
import AdminDisableFidReducer from "./admin_disable_fid_reducer";
import AdminFinalizeGreaterRealmReleaseV1Reducer from "./admin_finalize_greater_realm_release_v_1_reducer";
import AdminImportGreaterRealmChunkV1Reducer from "./admin_import_greater_realm_chunk_v_1_reducer";
import AdminImportGreaterRealmComponentsV1Reducer from "./admin_import_greater_realm_components_v_1_reducer";
import AdminImportGreaterRealmRegionsV1Reducer from "./admin_import_greater_realm_regions_v_1_reducer";
import AdminResetAccessRequestV1Reducer from "./admin_reset_access_request_v_1_reducer";
import AdminStageGreaterRealmReleaseV1Reducer from "./admin_stage_greater_realm_release_v_1_reducer";
import AdminUpsertRealmProfileV1Reducer from "./admin_upsert_realm_profile_v_1_reducer";
import AdminVerifyGreaterRealmBatchV1Reducer from "./admin_verify_greater_realm_batch_v_1_reducer";
import BootstrapPlayerReducer from "./bootstrap_player_reducer";
import BootstrapPlayerV2Reducer from "./bootstrap_player_v_2_reducer";

// Import all procedure arg schemas
import * as AccessRequestGetStatusV1Procedure from "./access_request_get_status_v_1_procedure";
import * as AccessRequestSubmitV1Procedure from "./access_request_submit_v_1_procedure";
import * as AdminGetGreaterRealmImportPlanV1Procedure from "./admin_get_greater_realm_import_plan_v_1_procedure";
import * as AdminGetGreaterRealmStatusV1Procedure from "./admin_get_greater_realm_status_v_1_procedure";
import * as AuthResolverGetFidAdmissionV2Procedure from "./auth_resolver_get_fid_admission_v_2_procedure";
import * as GetMyAdmissionStatusV2Procedure from "./get_my_admission_status_v_2_procedure";
import * as GetRealmStatusV1Procedure from "./get_realm_status_v_1_procedure";

// Import all table schema definitions
import AccessRequestV1Row from "./access_request_v_1_table";
import AdminAuditRow from "./admin_audit_table";
import AllowedFidRow from "./allowed_fid_table";
import AlphaTermsAcceptanceV1Row from "./alpha_terms_acceptance_v_1_table";
import CastleRow from "./castle_table";
import GreaterRealmActivationV1Row from "./greater_realm_activation_v_1_table";
import GreaterRealmCastleClaimV1Row from "./greater_realm_castle_claim_v_1_table";
import GreaterRealmCastleSlotV1Row from "./greater_realm_castle_slot_v_1_table";
import GreaterRealmCellOccupancyV1Row from "./greater_realm_cell_occupancy_v_1_table";
import GreaterRealmCellV1Row from "./greater_realm_cell_v_1_table";
import GreaterRealmChunkV1Row from "./greater_realm_chunk_v_1_table";
import GreaterRealmNavigationComponentV1Row from "./greater_realm_navigation_component_v_1_table";
import GreaterRealmReleaseV1Row from "./greater_realm_release_v_1_table";
import GreaterRealmResourceNodeV1Row from "./greater_realm_resource_node_v_1_table";
import MarkAccountV1Row from "./mark_account_v_1_table";
import PlayerRow from "./player_table";
import PlayerOwnershipV2Row from "./player_ownership_v_2_table";
import PlayerV2Row from "./player_v_2_table";
import RealmAtlasV1Row from "./realm_atlas_v_1_table";
import RealmAtlasVisibleRegionV1Row from "./realm_atlas_visible_region_v_1_table";
import RealmProfileV1Row from "./realm_profile_v_1_table";
import RealmWorkerSystemV2Row from "./realm_worker_system_v_2_table";
import ResourceAccountV1Row from "./resource_account_v_1_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  accessRequestV1: __table({
    name: 'access_request_v1',
    indexes: [
      { accessor: 'fid', name: 'access_request_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'access_request_v1_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, AccessRequestV1Row),
  adminAudit: __table({
    name: 'admin_audit',
    indexes: [
      { accessor: 'id', name: 'admin_audit_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'admin_audit_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AdminAuditRow),
  allowedFid: __table({
    name: 'allowed_fid',
    indexes: [
      { accessor: 'fid', name: 'allowed_fid_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'allowed_fid_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, AllowedFidRow),
  alphaTermsAcceptanceV1: __table({
    name: 'alpha_terms_acceptance_v1',
    indexes: [
      { accessor: 'acceptanceKey', name: 'alpha_terms_acceptance_v1_acceptance_key_idx_btree', algorithm: 'btree', columns: [
        'acceptanceKey',
      ] },
      { accessor: 'fid', name: 'alpha_terms_acceptance_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'alpha_terms_acceptance_v1_acceptance_key_key', constraint: 'unique', columns: ['acceptanceKey'] },
    ],
  }, AlphaTermsAcceptanceV1Row),
  castle: __table({
    name: 'castle',
    indexes: [
      { accessor: 'castleId', name: 'castle_castle_id_idx_btree', algorithm: 'btree', columns: [
        'castleId',
      ] },
      { accessor: 'ownerFid', name: 'castle_owner_fid_idx_btree', algorithm: 'btree', columns: [
        'ownerFid',
      ] },
      { accessor: 'tileKey', name: 'castle_tile_key_idx_btree', algorithm: 'btree', columns: [
        'tileKey',
      ] },
    ],
    constraints: [
      { name: 'castle_castle_id_key', constraint: 'unique', columns: ['castleId'] },
      { name: 'castle_owner_fid_key', constraint: 'unique', columns: ['ownerFid'] },
      { name: 'castle_tile_key_key', constraint: 'unique', columns: ['tileKey'] },
    ],
  }, CastleRow),
  greaterRealmActivationV1: __table({
    name: 'greater_realm_activation_v1',
    indexes: [
      { accessor: 'activationId', name: 'greater_realm_activation_v1_activation_id_idx_btree', algorithm: 'btree', columns: [
        'activationId',
      ] },
      { accessor: 'atlasId', name: 'greater_realm_activation_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_activation_v1_activation_id_key', constraint: 'unique', columns: ['activationId'] },
      { name: 'greater_realm_activation_v1_atlas_id_key', constraint: 'unique', columns: ['atlasId'] },
    ],
  }, GreaterRealmActivationV1Row),
  greaterRealmCastleClaimV1: __table({
    name: 'greater_realm_castle_claim_v1',
    indexes: [
      { accessor: 'activationId', name: 'greater_realm_castle_claim_v1_activation_id_idx_btree', algorithm: 'btree', columns: [
        'activationId',
      ] },
      { accessor: 'allocationSequence', name: 'greater_realm_castle_claim_v1_allocation_sequence_idx_btree', algorithm: 'btree', columns: [
        'allocationSequence',
      ] },
      { accessor: 'atlasId', name: 'greater_realm_castle_claim_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'castleId', name: 'greater_realm_castle_claim_v1_castle_id_idx_btree', algorithm: 'btree', columns: [
        'castleId',
      ] },
      { accessor: 'ownerFid', name: 'greater_realm_castle_claim_v1_owner_fid_idx_btree', algorithm: 'btree', columns: [
        'ownerFid',
      ] },
      { accessor: 'slotId', name: 'greater_realm_castle_claim_v1_slot_id_idx_btree', algorithm: 'btree', columns: [
        'slotId',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_castle_claim_v1_allocation_sequence_key', constraint: 'unique', columns: ['allocationSequence'] },
      { name: 'greater_realm_castle_claim_v1_castle_id_key', constraint: 'unique', columns: ['castleId'] },
      { name: 'greater_realm_castle_claim_v1_owner_fid_key', constraint: 'unique', columns: ['ownerFid'] },
      { name: 'greater_realm_castle_claim_v1_slot_id_key', constraint: 'unique', columns: ['slotId'] },
    ],
  }, GreaterRealmCastleClaimV1Row),
  greaterRealmCastleSlotV1: __table({
    name: 'greater_realm_castle_slot_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_castle_slot_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'cellKey', name: 'greater_realm_castle_slot_v1_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'componentKey', name: 'greater_realm_castle_slot_v1_component_key_idx_btree', algorithm: 'btree', columns: [
        'componentKey',
      ] },
      { accessor: 'regionId', name: 'greater_realm_castle_slot_v1_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { accessor: 'releaseOrdinal', name: 'greater_realm_castle_slot_v1_release_ordinal_idx_btree', algorithm: 'btree', columns: [
        'releaseOrdinal',
      ] },
      { accessor: 'slotId', name: 'greater_realm_castle_slot_v1_slot_id_idx_btree', algorithm: 'btree', columns: [
        'slotId',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_castle_slot_v1_cell_key_key', constraint: 'unique', columns: ['cellKey'] },
      { name: 'greater_realm_castle_slot_v1_release_ordinal_key', constraint: 'unique', columns: ['releaseOrdinal'] },
      { name: 'greater_realm_castle_slot_v1_slot_id_key', constraint: 'unique', columns: ['slotId'] },
    ],
  }, GreaterRealmCastleSlotV1Row),
  greaterRealmCellOccupancyV1: __table({
    name: 'greater_realm_cell_occupancy_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_cell_occupancy_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'castleId', name: 'greater_realm_cell_occupancy_v1_castle_id_idx_btree', algorithm: 'btree', columns: [
        'castleId',
      ] },
      { accessor: 'cellKey', name: 'greater_realm_cell_occupancy_v1_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'regionId', name: 'greater_realm_cell_occupancy_v1_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_cell_occupancy_v1_castle_id_key', constraint: 'unique', columns: ['castleId'] },
      { name: 'greater_realm_cell_occupancy_v1_cell_key_key', constraint: 'unique', columns: ['cellKey'] },
    ],
  }, GreaterRealmCellOccupancyV1Row),
  greaterRealmCellV1: __table({
    name: 'greater_realm_cell_v1',
    indexes: [
      { accessor: 'atlasCoordKey', name: 'greater_realm_cell_v1_atlas_coord_key_idx_btree', algorithm: 'btree', columns: [
        'atlasCoordKey',
      ] },
      { accessor: 'atlasId', name: 'greater_realm_cell_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'byAtlasAndReleaseOrdinal', name: 'greater_realm_cell_v1_atlas_id_release_ordinal_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
        'releaseOrdinal',
      ] },
      { accessor: 'cellKey', name: 'greater_realm_cell_v1_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'chunkHandle', name: 'greater_realm_cell_v1_chunk_handle_idx_btree', algorithm: 'btree', columns: [
        'chunkHandle',
      ] },
      { accessor: 'byChunkAndReleaseOrdinal', name: 'greater_realm_cell_v1_chunk_handle_release_ordinal_idx_btree', algorithm: 'btree', columns: [
        'chunkHandle',
        'releaseOrdinal',
      ] },
      { accessor: 'byComponentAndRouteDepth', name: 'greater_realm_cell_v1_component_key_route_depth_idx_btree', algorithm: 'btree', columns: [
        'componentKey',
        'routeDepth',
      ] },
      { accessor: 'regionId', name: 'greater_realm_cell_v1_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { accessor: 'releaseOrdinal', name: 'greater_realm_cell_v1_release_ordinal_idx_btree', algorithm: 'btree', columns: [
        'releaseOrdinal',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_cell_v1_atlas_coord_key_key', constraint: 'unique', columns: ['atlasCoordKey'] },
      { name: 'greater_realm_cell_v1_cell_key_key', constraint: 'unique', columns: ['cellKey'] },
      { name: 'greater_realm_cell_v1_release_ordinal_key', constraint: 'unique', columns: ['releaseOrdinal'] },
    ],
  }, GreaterRealmCellV1Row),
  greaterRealmChunkV1: __table({
    name: 'greater_realm_chunk_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_chunk_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'byAtlasAndImportOrdinal', name: 'greater_realm_chunk_v1_atlas_id_import_ordinal_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
        'importOrdinal',
      ] },
      { accessor: 'chunkCoordKey', name: 'greater_realm_chunk_v1_chunk_coord_key_idx_btree', algorithm: 'btree', columns: [
        'chunkCoordKey',
      ] },
      { accessor: 'chunkHandle', name: 'greater_realm_chunk_v1_chunk_handle_idx_btree', algorithm: 'btree', columns: [
        'chunkHandle',
      ] },
      { accessor: 'importOrdinal', name: 'greater_realm_chunk_v1_import_ordinal_idx_btree', algorithm: 'btree', columns: [
        'importOrdinal',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_chunk_v1_chunk_coord_key_key', constraint: 'unique', columns: ['chunkCoordKey'] },
      { name: 'greater_realm_chunk_v1_chunk_handle_key', constraint: 'unique', columns: ['chunkHandle'] },
      { name: 'greater_realm_chunk_v1_import_ordinal_key', constraint: 'unique', columns: ['importOrdinal'] },
    ],
  }, GreaterRealmChunkV1Row),
  greaterRealmNavigationComponentV1: __table({
    name: 'greater_realm_navigation_component_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_navigation_component_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'componentKey', name: 'greater_realm_navigation_component_v1_component_key_idx_btree', algorithm: 'btree', columns: [
        'componentKey',
      ] },
      { accessor: 'componentOrdinal', name: 'greater_realm_navigation_component_v1_component_ordinal_idx_btree', algorithm: 'btree', columns: [
        'componentOrdinal',
      ] },
      { accessor: 'rootCellKey', name: 'greater_realm_navigation_component_v1_root_cell_key_idx_btree', algorithm: 'btree', columns: [
        'rootCellKey',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_navigation_component_v1_component_key_key', constraint: 'unique', columns: ['componentKey'] },
      { name: 'greater_realm_navigation_component_v1_component_ordinal_key', constraint: 'unique', columns: ['componentOrdinal'] },
      { name: 'greater_realm_navigation_component_v1_root_cell_key_key', constraint: 'unique', columns: ['rootCellKey'] },
    ],
  }, GreaterRealmNavigationComponentV1Row),
  greaterRealmReleaseV1: __table({
    name: 'greater_realm_release_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_release_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'publicApprovalReceiptId', name: 'greater_realm_release_v1_public_approval_receipt_id_idx_btree', algorithm: 'btree', columns: [
        'publicApprovalReceiptId',
      ] },
      { accessor: 'publicReleaseId', name: 'greater_realm_release_v1_public_release_id_idx_btree', algorithm: 'btree', columns: [
        'publicReleaseId',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_release_v1_atlas_id_key', constraint: 'unique', columns: ['atlasId'] },
      { name: 'greater_realm_release_v1_public_approval_receipt_id_key', constraint: 'unique', columns: ['publicApprovalReceiptId'] },
      { name: 'greater_realm_release_v1_public_release_id_key', constraint: 'unique', columns: ['publicReleaseId'] },
    ],
  }, GreaterRealmReleaseV1Row),
  greaterRealmResourceNodeV1: __table({
    name: 'greater_realm_resource_node_v1',
    indexes: [
      { accessor: 'atlasId', name: 'greater_realm_resource_node_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'cellKey', name: 'greater_realm_resource_node_v1_cell_key_idx_btree', algorithm: 'btree', columns: [
        'cellKey',
      ] },
      { accessor: 'componentKey', name: 'greater_realm_resource_node_v1_component_key_idx_btree', algorithm: 'btree', columns: [
        'componentKey',
      ] },
      { accessor: 'byComponentAndResourceKind', name: 'greater_realm_resource_node_v1_component_key_resource_kind_idx_btree', algorithm: 'btree', columns: [
        'componentKey',
        'resourceKind',
      ] },
      { accessor: 'locationId', name: 'greater_realm_resource_node_v1_location_id_idx_btree', algorithm: 'btree', columns: [
        'locationId',
      ] },
      { accessor: 'nodeId', name: 'greater_realm_resource_node_v1_node_id_idx_btree', algorithm: 'btree', columns: [
        'nodeId',
      ] },
      { accessor: 'regionId', name: 'greater_realm_resource_node_v1_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
      { accessor: 'releaseOrdinal', name: 'greater_realm_resource_node_v1_release_ordinal_idx_btree', algorithm: 'btree', columns: [
        'releaseOrdinal',
      ] },
      { accessor: 'resourceKind', name: 'greater_realm_resource_node_v1_resource_kind_idx_btree', algorithm: 'btree', columns: [
        'resourceKind',
      ] },
    ],
    constraints: [
      { name: 'greater_realm_resource_node_v1_node_id_key', constraint: 'unique', columns: ['nodeId'] },
      { name: 'greater_realm_resource_node_v1_release_ordinal_key', constraint: 'unique', columns: ['releaseOrdinal'] },
    ],
  }, GreaterRealmResourceNodeV1Row),
  markAccountV1: __table({
    name: 'mark_account_v1',
    indexes: [
      { accessor: 'fid', name: 'mark_account_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'mark_account_v1_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, MarkAccountV1Row),
  player: __table({
    name: 'player',
    indexes: [
      { accessor: 'fid', name: 'player_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
      { accessor: 'identity', name: 'player_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_fid_key', constraint: 'unique', columns: ['fid'] },
      { name: 'player_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerOwnershipV2: __table({
    name: 'player_ownership_v2',
    indexes: [
      { accessor: 'fid', name: 'player_ownership_v2_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
      { accessor: 'identity', name: 'player_ownership_v2_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_ownership_v2_fid_key', constraint: 'unique', columns: ['fid'] },
      { name: 'player_ownership_v2_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerOwnershipV2Row),
  playerV2: __table({
    name: 'player_v2',
    indexes: [
      { accessor: 'fid', name: 'player_v2_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'player_v2_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, PlayerV2Row),
  realmAtlasV1: __table({
    name: 'realm_atlas_v1',
    indexes: [
      { accessor: 'atlasId', name: 'realm_atlas_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'publicReleaseId', name: 'realm_atlas_v1_public_release_id_idx_btree', algorithm: 'btree', columns: [
        'publicReleaseId',
      ] },
    ],
    constraints: [
      { name: 'realm_atlas_v1_atlas_id_key', constraint: 'unique', columns: ['atlasId'] },
      { name: 'realm_atlas_v1_public_release_id_key', constraint: 'unique', columns: ['publicReleaseId'] },
    ],
  }, RealmAtlasV1Row),
  realmAtlasVisibleRegionV1: __table({
    name: 'realm_atlas_visible_region_v1',
    indexes: [
      { accessor: 'atlasId', name: 'realm_atlas_visible_region_v1_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
      { accessor: 'ordinal', name: 'realm_atlas_visible_region_v1_ordinal_idx_btree', algorithm: 'btree', columns: [
        'ordinal',
      ] },
      { accessor: 'regionId', name: 'realm_atlas_visible_region_v1_region_id_idx_btree', algorithm: 'btree', columns: [
        'regionId',
      ] },
    ],
    constraints: [
      { name: 'realm_atlas_visible_region_v1_ordinal_key', constraint: 'unique', columns: ['ordinal'] },
      { name: 'realm_atlas_visible_region_v1_region_id_key', constraint: 'unique', columns: ['regionId'] },
    ],
  }, RealmAtlasVisibleRegionV1Row),
  realmProfileV1: __table({
    name: 'realm_profile_v1',
    indexes: [
      { accessor: 'fid', name: 'realm_profile_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
    ],
    constraints: [
      { name: 'realm_profile_v1_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, RealmProfileV1Row),
  realmWorkerSystemV2: __table({
    name: 'realm_worker_system_v2',
    indexes: [
      { accessor: 'atlasId', name: 'realm_worker_system_v2_atlas_id_idx_btree', algorithm: 'btree', columns: [
        'atlasId',
      ] },
    ],
    constraints: [
      { name: 'realm_worker_system_v2_atlas_id_key', constraint: 'unique', columns: ['atlasId'] },
    ],
  }, RealmWorkerSystemV2Row),
  resourceAccountV1: __table({
    name: 'resource_account_v1',
    indexes: [
      { accessor: 'castleId', name: 'resource_account_v1_castle_id_idx_btree', algorithm: 'btree', columns: [
        'castleId',
      ] },
      { accessor: 'fid', name: 'resource_account_v1_fid_idx_btree', algorithm: 'btree', columns: [
        'fid',
      ] },
      { accessor: 'realmId', name: 'resource_account_v1_realm_id_idx_btree', algorithm: 'btree', columns: [
        'realmId',
      ] },
    ],
    constraints: [
      { name: 'resource_account_v1_castle_id_key', constraint: 'unique', columns: ['castleId'] },
      { name: 'resource_account_v1_fid_key', constraint: 'unique', columns: ['fid'] },
    ],
  }, ResourceAccountV1Row),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_alpha_terms_v1", AcceptAlphaTermsV1Reducer),
  __reducerSchema("admin_admit_founder_for_access_request_v2", AdminAdmitFounderForAccessRequestV2Reducer),
  __reducerSchema("admin_admit_founder_v1", AdminAdmitFounderV1Reducer),
  __reducerSchema("admin_allow_fid", AdminAllowFidReducer),
  __reducerSchema("admin_allow_fid_for_access_request_v1", AdminAllowFidForAccessRequestV1Reducer),
  __reducerSchema("admin_begin_greater_realm_verification_v1", AdminBeginGreaterRealmVerificationV1Reducer),
  __reducerSchema("admin_bump_auth_epoch", AdminBumpAuthEpochReducer),
  __reducerSchema("admin_disable_fid", AdminDisableFidReducer),
  __reducerSchema("admin_finalize_greater_realm_release_v1", AdminFinalizeGreaterRealmReleaseV1Reducer),
  __reducerSchema("admin_import_greater_realm_chunk_v1", AdminImportGreaterRealmChunkV1Reducer),
  __reducerSchema("admin_import_greater_realm_components_v1", AdminImportGreaterRealmComponentsV1Reducer),
  __reducerSchema("admin_import_greater_realm_regions_v1", AdminImportGreaterRealmRegionsV1Reducer),
  __reducerSchema("admin_reset_access_request_v1", AdminResetAccessRequestV1Reducer),
  __reducerSchema("admin_stage_greater_realm_release_v1", AdminStageGreaterRealmReleaseV1Reducer),
  __reducerSchema("admin_upsert_realm_profile_v1", AdminUpsertRealmProfileV1Reducer),
  __reducerSchema("admin_verify_greater_realm_batch_v1", AdminVerifyGreaterRealmBatchV1Reducer),
  __reducerSchema("bootstrap_player", BootstrapPlayerReducer),
  __reducerSchema("bootstrap_player_v2", BootstrapPlayerV2Reducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("access_request_get_status_v_1", AccessRequestGetStatusV1Procedure.params, AccessRequestGetStatusV1Procedure.returnType),
  __procedureSchema("access_request_submit_v_1", AccessRequestSubmitV1Procedure.params, AccessRequestSubmitV1Procedure.returnType),
  __procedureSchema("admin_get_greater_realm_import_plan_v_1", AdminGetGreaterRealmImportPlanV1Procedure.params, AdminGetGreaterRealmImportPlanV1Procedure.returnType),
  __procedureSchema("admin_get_greater_realm_status_v_1", AdminGetGreaterRealmStatusV1Procedure.params, AdminGetGreaterRealmStatusV1Procedure.returnType),
  __procedureSchema("auth_resolver_get_fid_admission_v_2", AuthResolverGetFidAdmissionV2Procedure.params, AuthResolverGetFidAdmissionV2Procedure.returnType),
  __procedureSchema("get_my_admission_status_v_2", GetMyAdmissionStatusV2Procedure.params, GetMyAdmissionStatusV2Procedure.returnType),
  __procedureSchema("get_realm_status_v1", GetRealmStatusV1Procedure.params, GetRealmStatusV1Procedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.6.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
