// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  Gameplay04InitializeResultV1,
} from "./types";

export const params = {
  sequence: __t.u64(),
  requestKey: __t.string(),
  expectedRevision: __t.u64(),
  policyVersion: __t.string(),
};
export const returnType = Gameplay04InitializeResultV1