// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fid: __t.u64().primaryKey(),
  totalSnapBurnedMicros: __t.u128().name("total_snap_burned_micros"),
  earnedMicros: __t.u128().name("earned_micros"),
  spentMicros: __t.u128().name("spent_micros"),
  balanceMicros: __t.u128().name("balance_micros"),
  policyVersion: __t.string().name("policy_version"),
  updatedAt: __t.timestamp().name("updated_at"),
});
