// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fid: __t.u64().primaryKey(),
  canonicalUsername: __t.option(__t.string()).name("canonical_username"),
  displayName: __t.option(__t.string()).name("display_name"),
  pfpUrl: __t.option(__t.string()).name("pfp_url"),
  publicBio: __t.option(__t.string()).name("public_bio"),
  admittedAt: __t.timestamp().name("admitted_at"),
  firstAuthenticatedAt: __t.option(__t.timestamp()).name("first_authenticated_at"),
  profileUpdatedAt: __t.timestamp().name("profile_updated_at"),
  publicStatus: __t.string().name("public_status"),
  communityStatsVisible: __t.bool().name("community_stats_visible"),
  totalSnapBurnedMicros: __t.option(__t.u128()).name("total_snap_burned_micros"),
  marksEarnedMicros: __t.option(__t.u128()).name("marks_earned_micros"),
  marksSpentMicros: __t.option(__t.u128()).name("marks_spent_micros"),
  marksBalanceMicros: __t.option(__t.u128()).name("marks_balance_micros"),
  marksPolicyVersion: __t.option(__t.string()).name("marks_policy_version"),
});
