// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  fid: __t.u64().primaryKey(),
  castleId: __t.u64().name("castle_id"),
  realmId: __t.string().name("realm_id"),
  food: __t.u64(),
  wood: __t.u64(),
  stone: __t.u64(),
  gold: __t.u64(),
  settledThroughMicros: __t.u64().name("settled_through_micros"),
  revision: __t.u64(),
  policyVersion: __t.string().name("policy_version"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
